{-
   Trello

   This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

   OpenAPI spec version: 2.0
   Trello API version: 1.0
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : Trello.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Trello.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import Trello.Model
import Trello.Core


-- * Actions

-- | 'actionsText' Lens
actionsTextL :: Lens_' Actions (Maybe Text)
actionsTextL f Actions{..} = (\actionsText -> Actions { actionsText, ..} ) <$> f actionsText
{-# INLINE actionsTextL #-}



-- * ActionsComments

-- | 'actionsCommentsText' Lens
actionsCommentsTextL :: Lens_' ActionsComments (Maybe Text)
actionsCommentsTextL f ActionsComments{..} = (\actionsCommentsText -> ActionsComments { actionsCommentsText, ..} ) <$> f actionsCommentsText
{-# INLINE actionsCommentsTextL #-}



-- * ActionsText

-- | 'actionsTextValue' Lens
actionsTextValueL :: Lens_' ActionsText (Maybe Text)
actionsTextValueL f ActionsText{..} = (\actionsTextValue -> ActionsText { actionsTextValue, ..} ) <$> f actionsTextValue
{-# INLINE actionsTextValueL #-}



-- * Boards

-- | 'boardsClosed' Lens
boardsClosedL :: Lens_' Boards (Maybe Text)
boardsClosedL f Boards{..} = (\boardsClosed -> Boards { boardsClosed, ..} ) <$> f boardsClosed
{-# INLINE boardsClosedL #-}

-- | 'boardsDesc' Lens
boardsDescL :: Lens_' Boards (Maybe Text)
boardsDescL f Boards{..} = (\boardsDesc -> Boards { boardsDesc, ..} ) <$> f boardsDesc
{-# INLINE boardsDescL #-}

-- | 'boardsIdBoardSource' Lens
boardsIdBoardSourceL :: Lens_' Boards (Maybe Text)
boardsIdBoardSourceL f Boards{..} = (\boardsIdBoardSource -> Boards { boardsIdBoardSource, ..} ) <$> f boardsIdBoardSource
{-# INLINE boardsIdBoardSourceL #-}

-- | 'boardsIdOrganization' Lens
boardsIdOrganizationL :: Lens_' Boards (Maybe Text)
boardsIdOrganizationL f Boards{..} = (\boardsIdOrganization -> Boards { boardsIdOrganization, ..} ) <$> f boardsIdOrganization
{-# INLINE boardsIdOrganizationL #-}

-- | 'boardsKeepFromSource' Lens
boardsKeepFromSourceL :: Lens_' Boards (Maybe Text)
boardsKeepFromSourceL f Boards{..} = (\boardsKeepFromSource -> Boards { boardsKeepFromSource, ..} ) <$> f boardsKeepFromSource
{-# INLINE boardsKeepFromSourceL #-}

-- | 'boardsLabelNamesblue' Lens
boardsLabelNamesblueL :: Lens_' Boards (Maybe Text)
boardsLabelNamesblueL f Boards{..} = (\boardsLabelNamesblue -> Boards { boardsLabelNamesblue, ..} ) <$> f boardsLabelNamesblue
{-# INLINE boardsLabelNamesblueL #-}

-- | 'boardsLabelNamesgreen' Lens
boardsLabelNamesgreenL :: Lens_' Boards (Maybe Text)
boardsLabelNamesgreenL f Boards{..} = (\boardsLabelNamesgreen -> Boards { boardsLabelNamesgreen, ..} ) <$> f boardsLabelNamesgreen
{-# INLINE boardsLabelNamesgreenL #-}

-- | 'boardsLabelNamesorange' Lens
boardsLabelNamesorangeL :: Lens_' Boards (Maybe Text)
boardsLabelNamesorangeL f Boards{..} = (\boardsLabelNamesorange -> Boards { boardsLabelNamesorange, ..} ) <$> f boardsLabelNamesorange
{-# INLINE boardsLabelNamesorangeL #-}

-- | 'boardsLabelNamespurple' Lens
boardsLabelNamespurpleL :: Lens_' Boards (Maybe Text)
boardsLabelNamespurpleL f Boards{..} = (\boardsLabelNamespurple -> Boards { boardsLabelNamespurple, ..} ) <$> f boardsLabelNamespurple
{-# INLINE boardsLabelNamespurpleL #-}

-- | 'boardsLabelNamesred' Lens
boardsLabelNamesredL :: Lens_' Boards (Maybe Text)
boardsLabelNamesredL f Boards{..} = (\boardsLabelNamesred -> Boards { boardsLabelNamesred, ..} ) <$> f boardsLabelNamesred
{-# INLINE boardsLabelNamesredL #-}

-- | 'boardsLabelNamesyellow' Lens
boardsLabelNamesyellowL :: Lens_' Boards (Maybe Text)
boardsLabelNamesyellowL f Boards{..} = (\boardsLabelNamesyellow -> Boards { boardsLabelNamesyellow, ..} ) <$> f boardsLabelNamesyellow
{-# INLINE boardsLabelNamesyellowL #-}

-- | 'boardsName' Lens
boardsNameL :: Lens_' Boards (Maybe Text)
boardsNameL f Boards{..} = (\boardsName -> Boards { boardsName, ..} ) <$> f boardsName
{-# INLINE boardsNameL #-}

-- | 'boardsPowerUps' Lens
boardsPowerUpsL :: Lens_' Boards (Maybe Text)
boardsPowerUpsL f Boards{..} = (\boardsPowerUps -> Boards { boardsPowerUps, ..} ) <$> f boardsPowerUps
{-# INLINE boardsPowerUpsL #-}

-- | 'boardsPrefsbackground' Lens
boardsPrefsbackgroundL :: Lens_' Boards (Maybe Text)
boardsPrefsbackgroundL f Boards{..} = (\boardsPrefsbackground -> Boards { boardsPrefsbackground, ..} ) <$> f boardsPrefsbackground
{-# INLINE boardsPrefsbackgroundL #-}

-- | 'boardsPrefscalendarFeedEnabled' Lens
boardsPrefscalendarFeedEnabledL :: Lens_' Boards (Maybe Text)
boardsPrefscalendarFeedEnabledL f Boards{..} = (\boardsPrefscalendarFeedEnabled -> Boards { boardsPrefscalendarFeedEnabled, ..} ) <$> f boardsPrefscalendarFeedEnabled
{-# INLINE boardsPrefscalendarFeedEnabledL #-}

-- | 'boardsPrefscardAging' Lens
boardsPrefscardAgingL :: Lens_' Boards (Maybe Text)
boardsPrefscardAgingL f Boards{..} = (\boardsPrefscardAging -> Boards { boardsPrefscardAging, ..} ) <$> f boardsPrefscardAging
{-# INLINE boardsPrefscardAgingL #-}

-- | 'boardsPrefscardCovers' Lens
boardsPrefscardCoversL :: Lens_' Boards (Maybe Text)
boardsPrefscardCoversL f Boards{..} = (\boardsPrefscardCovers -> Boards { boardsPrefscardCovers, ..} ) <$> f boardsPrefscardCovers
{-# INLINE boardsPrefscardCoversL #-}

-- | 'boardsPrefscomments' Lens
boardsPrefscommentsL :: Lens_' Boards (Maybe Text)
boardsPrefscommentsL f Boards{..} = (\boardsPrefscomments -> Boards { boardsPrefscomments, ..} ) <$> f boardsPrefscomments
{-# INLINE boardsPrefscommentsL #-}

-- | 'boardsPrefsinvitations' Lens
boardsPrefsinvitationsL :: Lens_' Boards (Maybe Text)
boardsPrefsinvitationsL f Boards{..} = (\boardsPrefsinvitations -> Boards { boardsPrefsinvitations, ..} ) <$> f boardsPrefsinvitations
{-# INLINE boardsPrefsinvitationsL #-}

-- | 'boardsPrefspermissionLevel' Lens
boardsPrefspermissionLevelL :: Lens_' Boards (Maybe Text)
boardsPrefspermissionLevelL f Boards{..} = (\boardsPrefspermissionLevel -> Boards { boardsPrefspermissionLevel, ..} ) <$> f boardsPrefspermissionLevel
{-# INLINE boardsPrefspermissionLevelL #-}

-- | 'boardsPrefsselfJoin' Lens
boardsPrefsselfJoinL :: Lens_' Boards (Maybe Text)
boardsPrefsselfJoinL f Boards{..} = (\boardsPrefsselfJoin -> Boards { boardsPrefsselfJoin, ..} ) <$> f boardsPrefsselfJoin
{-# INLINE boardsPrefsselfJoinL #-}

-- | 'boardsPrefsvoting' Lens
boardsPrefsvotingL :: Lens_' Boards (Maybe Text)
boardsPrefsvotingL f Boards{..} = (\boardsPrefsvoting -> Boards { boardsPrefsvoting, ..} ) <$> f boardsPrefsvoting
{-# INLINE boardsPrefsvotingL #-}

-- | 'boardsPrefsBackground' Lens
boardsPrefsBackgroundL :: Lens_' Boards (Maybe Text)
boardsPrefsBackgroundL f Boards{..} = (\boardsPrefsBackground -> Boards { boardsPrefsBackground, ..} ) <$> f boardsPrefsBackground
{-# INLINE boardsPrefsBackgroundL #-}

-- | 'boardsPrefsCardAging' Lens
boardsPrefsCardAgingL :: Lens_' Boards (Maybe Text)
boardsPrefsCardAgingL f Boards{..} = (\boardsPrefsCardAging -> Boards { boardsPrefsCardAging, ..} ) <$> f boardsPrefsCardAging
{-# INLINE boardsPrefsCardAgingL #-}

-- | 'boardsPrefsCardCovers' Lens
boardsPrefsCardCoversL :: Lens_' Boards (Maybe Text)
boardsPrefsCardCoversL f Boards{..} = (\boardsPrefsCardCovers -> Boards { boardsPrefsCardCovers, ..} ) <$> f boardsPrefsCardCovers
{-# INLINE boardsPrefsCardCoversL #-}

-- | 'boardsPrefsComments' Lens
boardsPrefsCommentsL :: Lens_' Boards (Maybe Text)
boardsPrefsCommentsL f Boards{..} = (\boardsPrefsComments -> Boards { boardsPrefsComments, ..} ) <$> f boardsPrefsComments
{-# INLINE boardsPrefsCommentsL #-}

-- | 'boardsPrefsInvitations' Lens
boardsPrefsInvitationsL :: Lens_' Boards (Maybe Text)
boardsPrefsInvitationsL f Boards{..} = (\boardsPrefsInvitations -> Boards { boardsPrefsInvitations, ..} ) <$> f boardsPrefsInvitations
{-# INLINE boardsPrefsInvitationsL #-}

-- | 'boardsPrefsPermissionLevel' Lens
boardsPrefsPermissionLevelL :: Lens_' Boards (Maybe Text)
boardsPrefsPermissionLevelL f Boards{..} = (\boardsPrefsPermissionLevel -> Boards { boardsPrefsPermissionLevel, ..} ) <$> f boardsPrefsPermissionLevel
{-# INLINE boardsPrefsPermissionLevelL #-}

-- | 'boardsPrefsSelfJoin' Lens
boardsPrefsSelfJoinL :: Lens_' Boards (Maybe Text)
boardsPrefsSelfJoinL f Boards{..} = (\boardsPrefsSelfJoin -> Boards { boardsPrefsSelfJoin, ..} ) <$> f boardsPrefsSelfJoin
{-# INLINE boardsPrefsSelfJoinL #-}

-- | 'boardsPrefsVoting' Lens
boardsPrefsVotingL :: Lens_' Boards (Maybe Text)
boardsPrefsVotingL f Boards{..} = (\boardsPrefsVoting -> Boards { boardsPrefsVoting, ..} ) <$> f boardsPrefsVoting
{-# INLINE boardsPrefsVotingL #-}

-- | 'boardsSubscribed' Lens
boardsSubscribedL :: Lens_' Boards (Maybe Text)
boardsSubscribedL f Boards{..} = (\boardsSubscribed -> Boards { boardsSubscribed, ..} ) <$> f boardsSubscribed
{-# INLINE boardsSubscribedL #-}



-- * BoardsChecklists

-- | 'boardsChecklistsName' Lens
boardsChecklistsNameL :: Lens_' BoardsChecklists (Maybe Text)
boardsChecklistsNameL f BoardsChecklists{..} = (\boardsChecklistsName -> BoardsChecklists { boardsChecklistsName, ..} ) <$> f boardsChecklistsName
{-# INLINE boardsChecklistsNameL #-}



-- * BoardsClosed

-- | 'boardsClosedValue' Lens
boardsClosedValueL :: Lens_' BoardsClosed (Maybe Text)
boardsClosedValueL f BoardsClosed{..} = (\boardsClosedValue -> BoardsClosed { boardsClosedValue, ..} ) <$> f boardsClosedValue
{-# INLINE boardsClosedValueL #-}



-- * BoardsDesc

-- | 'boardsDescValue' Lens
boardsDescValueL :: Lens_' BoardsDesc (Maybe Text)
boardsDescValueL f BoardsDesc{..} = (\boardsDescValue -> BoardsDesc { boardsDescValue, ..} ) <$> f boardsDescValue
{-# INLINE boardsDescValueL #-}



-- * BoardsIdOrganization

-- | 'boardsIdOrganizationValue' Lens
boardsIdOrganizationValueL :: Lens_' BoardsIdOrganization (Maybe Text)
boardsIdOrganizationValueL f BoardsIdOrganization{..} = (\boardsIdOrganizationValue -> BoardsIdOrganization { boardsIdOrganizationValue, ..} ) <$> f boardsIdOrganizationValue
{-# INLINE boardsIdOrganizationValueL #-}



-- * BoardsLabels

-- | 'boardsLabelsColor' Lens
boardsLabelsColorL :: Lens_' BoardsLabels (Maybe Text)
boardsLabelsColorL f BoardsLabels{..} = (\boardsLabelsColor -> BoardsLabels { boardsLabelsColor, ..} ) <$> f boardsLabelsColor
{-# INLINE boardsLabelsColorL #-}

-- | 'boardsLabelsName' Lens
boardsLabelsNameL :: Lens_' BoardsLabels (Maybe Text)
boardsLabelsNameL f BoardsLabels{..} = (\boardsLabelsName -> BoardsLabels { boardsLabelsName, ..} ) <$> f boardsLabelsName
{-# INLINE boardsLabelsNameL #-}



-- * BoardsLists

-- | 'boardsListsName' Lens
boardsListsNameL :: Lens_' BoardsLists (Maybe Text)
boardsListsNameL f BoardsLists{..} = (\boardsListsName -> BoardsLists { boardsListsName, ..} ) <$> f boardsListsName
{-# INLINE boardsListsNameL #-}

-- | 'boardsListsPos' Lens
boardsListsPosL :: Lens_' BoardsLists (Maybe Text)
boardsListsPosL f BoardsLists{..} = (\boardsListsPos -> BoardsLists { boardsListsPos, ..} ) <$> f boardsListsPos
{-# INLINE boardsListsPosL #-}



-- * BoardsMembers

-- | 'boardsMembersEmail' Lens
boardsMembersEmailL :: Lens_' BoardsMembers (Maybe Text)
boardsMembersEmailL f BoardsMembers{..} = (\boardsMembersEmail -> BoardsMembers { boardsMembersEmail, ..} ) <$> f boardsMembersEmail
{-# INLINE boardsMembersEmailL #-}

-- | 'boardsMembersFullName' Lens
boardsMembersFullNameL :: Lens_' BoardsMembers (Maybe Text)
boardsMembersFullNameL f BoardsMembers{..} = (\boardsMembersFullName -> BoardsMembers { boardsMembersFullName, ..} ) <$> f boardsMembersFullName
{-# INLINE boardsMembersFullNameL #-}

-- | 'boardsMembersType' Lens
boardsMembersTypeL :: Lens_' BoardsMembers (Maybe Text)
boardsMembersTypeL f BoardsMembers{..} = (\boardsMembersType -> BoardsMembers { boardsMembersType, ..} ) <$> f boardsMembersType
{-# INLINE boardsMembersTypeL #-}



-- * BoardsMemberships

-- | 'boardsMembershipsMemberFields' Lens
boardsMembershipsMemberFieldsL :: Lens_' BoardsMemberships (Maybe Text)
boardsMembershipsMemberFieldsL f BoardsMemberships{..} = (\boardsMembershipsMemberFields -> BoardsMemberships { boardsMembershipsMemberFields, ..} ) <$> f boardsMembershipsMemberFields
{-# INLINE boardsMembershipsMemberFieldsL #-}

-- | 'boardsMembershipsType' Lens
boardsMembershipsTypeL :: Lens_' BoardsMemberships (Maybe Text)
boardsMembershipsTypeL f BoardsMemberships{..} = (\boardsMembershipsType -> BoardsMemberships { boardsMembershipsType, ..} ) <$> f boardsMembershipsType
{-# INLINE boardsMembershipsTypeL #-}



-- * BoardsName

-- | 'boardsNameValue' Lens
boardsNameValueL :: Lens_' BoardsName (Maybe Text)
boardsNameValueL f BoardsName{..} = (\boardsNameValue -> BoardsName { boardsNameValue, ..} ) <$> f boardsNameValue
{-# INLINE boardsNameValueL #-}



-- * BoardsPowerUps

-- | 'boardsPowerUpsValue' Lens
boardsPowerUpsValueL :: Lens_' BoardsPowerUps (Maybe Text)
boardsPowerUpsValueL f BoardsPowerUps{..} = (\boardsPowerUpsValue -> BoardsPowerUps { boardsPowerUpsValue, ..} ) <$> f boardsPowerUpsValue
{-# INLINE boardsPowerUpsValueL #-}



-- * BoardsSubscribed

-- | 'boardsSubscribedValue' Lens
boardsSubscribedValueL :: Lens_' BoardsSubscribed (Maybe Text)
boardsSubscribedValueL f BoardsSubscribed{..} = (\boardsSubscribedValue -> BoardsSubscribed { boardsSubscribedValue, ..} ) <$> f boardsSubscribedValue
{-# INLINE boardsSubscribedValueL #-}



-- * Cards

-- | 'cardsClosed' Lens
cardsClosedL :: Lens_' Cards (Maybe Text)
cardsClosedL f Cards{..} = (\cardsClosed -> Cards { cardsClosed, ..} ) <$> f cardsClosed
{-# INLINE cardsClosedL #-}

-- | 'cardsDesc' Lens
cardsDescL :: Lens_' Cards (Maybe Text)
cardsDescL f Cards{..} = (\cardsDesc -> Cards { cardsDesc, ..} ) <$> f cardsDesc
{-# INLINE cardsDescL #-}

-- | 'cardsDue' Lens
cardsDueL :: Lens_' Cards (Maybe Text)
cardsDueL f Cards{..} = (\cardsDue -> Cards { cardsDue, ..} ) <$> f cardsDue
{-# INLINE cardsDueL #-}

-- | 'cardsFileSource' Lens
cardsFileSourceL :: Lens_' Cards (Maybe Text)
cardsFileSourceL f Cards{..} = (\cardsFileSource -> Cards { cardsFileSource, ..} ) <$> f cardsFileSource
{-# INLINE cardsFileSourceL #-}

-- | 'cardsIdAttachmentCover' Lens
cardsIdAttachmentCoverL :: Lens_' Cards (Maybe Text)
cardsIdAttachmentCoverL f Cards{..} = (\cardsIdAttachmentCover -> Cards { cardsIdAttachmentCover, ..} ) <$> f cardsIdAttachmentCover
{-# INLINE cardsIdAttachmentCoverL #-}

-- | 'cardsIdBoard' Lens
cardsIdBoardL :: Lens_' Cards (Maybe Text)
cardsIdBoardL f Cards{..} = (\cardsIdBoard -> Cards { cardsIdBoard, ..} ) <$> f cardsIdBoard
{-# INLINE cardsIdBoardL #-}

-- | 'cardsIdCardSource' Lens
cardsIdCardSourceL :: Lens_' Cards (Maybe Text)
cardsIdCardSourceL f Cards{..} = (\cardsIdCardSource -> Cards { cardsIdCardSource, ..} ) <$> f cardsIdCardSource
{-# INLINE cardsIdCardSourceL #-}

-- | 'cardsIdLabels' Lens
cardsIdLabelsL :: Lens_' Cards (Maybe Text)
cardsIdLabelsL f Cards{..} = (\cardsIdLabels -> Cards { cardsIdLabels, ..} ) <$> f cardsIdLabels
{-# INLINE cardsIdLabelsL #-}

-- | 'cardsIdList' Lens
cardsIdListL :: Lens_' Cards (Maybe Text)
cardsIdListL f Cards{..} = (\cardsIdList -> Cards { cardsIdList, ..} ) <$> f cardsIdList
{-# INLINE cardsIdListL #-}

-- | 'cardsIdMembers' Lens
cardsIdMembersL :: Lens_' Cards (Maybe Text)
cardsIdMembersL f Cards{..} = (\cardsIdMembers -> Cards { cardsIdMembers, ..} ) <$> f cardsIdMembers
{-# INLINE cardsIdMembersL #-}

-- | 'cardsKeepFromSource' Lens
cardsKeepFromSourceL :: Lens_' Cards (Maybe Text)
cardsKeepFromSourceL f Cards{..} = (\cardsKeepFromSource -> Cards { cardsKeepFromSource, ..} ) <$> f cardsKeepFromSource
{-# INLINE cardsKeepFromSourceL #-}

-- | 'cardsLabels' Lens
cardsLabelsL :: Lens_' Cards (Maybe Text)
cardsLabelsL f Cards{..} = (\cardsLabels -> Cards { cardsLabels, ..} ) <$> f cardsLabels
{-# INLINE cardsLabelsL #-}

-- | 'cardsName' Lens
cardsNameL :: Lens_' Cards (Maybe Text)
cardsNameL f Cards{..} = (\cardsName -> Cards { cardsName, ..} ) <$> f cardsName
{-# INLINE cardsNameL #-}

-- | 'cardsPos' Lens
cardsPosL :: Lens_' Cards (Maybe Text)
cardsPosL f Cards{..} = (\cardsPos -> Cards { cardsPos, ..} ) <$> f cardsPos
{-# INLINE cardsPosL #-}

-- | 'cardsSubscribed' Lens
cardsSubscribedL :: Lens_' Cards (Maybe Text)
cardsSubscribedL f Cards{..} = (\cardsSubscribed -> Cards { cardsSubscribed, ..} ) <$> f cardsSubscribed
{-# INLINE cardsSubscribedL #-}

-- | 'cardsUrlSource' Lens
cardsUrlSourceL :: Lens_' Cards (Maybe Text)
cardsUrlSourceL f Cards{..} = (\cardsUrlSource -> Cards { cardsUrlSource, ..} ) <$> f cardsUrlSource
{-# INLINE cardsUrlSourceL #-}



-- * CardsActionsComments

-- | 'cardsActionsCommentsText' Lens
cardsActionsCommentsTextL :: Lens_' CardsActionsComments (Maybe Text)
cardsActionsCommentsTextL f CardsActionsComments{..} = (\cardsActionsCommentsText -> CardsActionsComments { cardsActionsCommentsText, ..} ) <$> f cardsActionsCommentsText
{-# INLINE cardsActionsCommentsTextL #-}



-- * CardsAttachments

-- | 'cardsAttachmentsFile' Lens
cardsAttachmentsFileL :: Lens_' CardsAttachments (Maybe Text)
cardsAttachmentsFileL f CardsAttachments{..} = (\cardsAttachmentsFile -> CardsAttachments { cardsAttachmentsFile, ..} ) <$> f cardsAttachmentsFile
{-# INLINE cardsAttachmentsFileL #-}

-- | 'cardsAttachmentsMimeType' Lens
cardsAttachmentsMimeTypeL :: Lens_' CardsAttachments (Maybe Text)
cardsAttachmentsMimeTypeL f CardsAttachments{..} = (\cardsAttachmentsMimeType -> CardsAttachments { cardsAttachmentsMimeType, ..} ) <$> f cardsAttachmentsMimeType
{-# INLINE cardsAttachmentsMimeTypeL #-}

-- | 'cardsAttachmentsName' Lens
cardsAttachmentsNameL :: Lens_' CardsAttachments (Maybe Text)
cardsAttachmentsNameL f CardsAttachments{..} = (\cardsAttachmentsName -> CardsAttachments { cardsAttachmentsName, ..} ) <$> f cardsAttachmentsName
{-# INLINE cardsAttachmentsNameL #-}

-- | 'cardsAttachmentsUrl' Lens
cardsAttachmentsUrlL :: Lens_' CardsAttachments (Maybe Text)
cardsAttachmentsUrlL f CardsAttachments{..} = (\cardsAttachmentsUrl -> CardsAttachments { cardsAttachmentsUrl, ..} ) <$> f cardsAttachmentsUrl
{-# INLINE cardsAttachmentsUrlL #-}



-- * CardsChecklistCheckItem

-- | 'cardsChecklistCheckItemName' Lens
cardsChecklistCheckItemNameL :: Lens_' CardsChecklistCheckItem (Maybe Text)
cardsChecklistCheckItemNameL f CardsChecklistCheckItem{..} = (\cardsChecklistCheckItemName -> CardsChecklistCheckItem { cardsChecklistCheckItemName, ..} ) <$> f cardsChecklistCheckItemName
{-# INLINE cardsChecklistCheckItemNameL #-}

-- | 'cardsChecklistCheckItemPos' Lens
cardsChecklistCheckItemPosL :: Lens_' CardsChecklistCheckItem (Maybe Text)
cardsChecklistCheckItemPosL f CardsChecklistCheckItem{..} = (\cardsChecklistCheckItemPos -> CardsChecklistCheckItem { cardsChecklistCheckItemPos, ..} ) <$> f cardsChecklistCheckItemPos
{-# INLINE cardsChecklistCheckItemPosL #-}



-- * CardsChecklistCheckItemName

-- | 'cardsChecklistCheckItemNameValue' Lens
cardsChecklistCheckItemNameValueL :: Lens_' CardsChecklistCheckItemName (Maybe Text)
cardsChecklistCheckItemNameValueL f CardsChecklistCheckItemName{..} = (\cardsChecklistCheckItemNameValue -> CardsChecklistCheckItemName { cardsChecklistCheckItemNameValue, ..} ) <$> f cardsChecklistCheckItemNameValue
{-# INLINE cardsChecklistCheckItemNameValueL #-}



-- * CardsChecklistCheckItemPos

-- | 'cardsChecklistCheckItemPosValue' Lens
cardsChecklistCheckItemPosValueL :: Lens_' CardsChecklistCheckItemPos (Maybe Text)
cardsChecklistCheckItemPosValueL f CardsChecklistCheckItemPos{..} = (\cardsChecklistCheckItemPosValue -> CardsChecklistCheckItemPos { cardsChecklistCheckItemPosValue, ..} ) <$> f cardsChecklistCheckItemPosValue
{-# INLINE cardsChecklistCheckItemPosValueL #-}



-- * CardsChecklistCheckItemState

-- | 'cardsChecklistCheckItemStateValue' Lens
cardsChecklistCheckItemStateValueL :: Lens_' CardsChecklistCheckItemState (Maybe Text)
cardsChecklistCheckItemStateValueL f CardsChecklistCheckItemState{..} = (\cardsChecklistCheckItemStateValue -> CardsChecklistCheckItemState { cardsChecklistCheckItemStateValue, ..} ) <$> f cardsChecklistCheckItemStateValue
{-# INLINE cardsChecklistCheckItemStateValueL #-}



-- * CardsChecklistIdChecklistCurrentCheckItem

-- | 'cardsChecklistIdChecklistCurrentCheckItemIdChecklist' Lens
cardsChecklistIdChecklistCurrentCheckItemIdChecklistL :: Lens_' CardsChecklistIdChecklistCurrentCheckItem (Maybe Text)
cardsChecklistIdChecklistCurrentCheckItemIdChecklistL f CardsChecklistIdChecklistCurrentCheckItem{..} = (\cardsChecklistIdChecklistCurrentCheckItemIdChecklist -> CardsChecklistIdChecklistCurrentCheckItem { cardsChecklistIdChecklistCurrentCheckItemIdChecklist, ..} ) <$> f cardsChecklistIdChecklistCurrentCheckItemIdChecklist
{-# INLINE cardsChecklistIdChecklistCurrentCheckItemIdChecklistL #-}

-- | 'cardsChecklistIdChecklistCurrentCheckItemName' Lens
cardsChecklistIdChecklistCurrentCheckItemNameL :: Lens_' CardsChecklistIdChecklistCurrentCheckItem (Maybe Text)
cardsChecklistIdChecklistCurrentCheckItemNameL f CardsChecklistIdChecklistCurrentCheckItem{..} = (\cardsChecklistIdChecklistCurrentCheckItemName -> CardsChecklistIdChecklistCurrentCheckItem { cardsChecklistIdChecklistCurrentCheckItemName, ..} ) <$> f cardsChecklistIdChecklistCurrentCheckItemName
{-# INLINE cardsChecklistIdChecklistCurrentCheckItemNameL #-}

-- | 'cardsChecklistIdChecklistCurrentCheckItemPos' Lens
cardsChecklistIdChecklistCurrentCheckItemPosL :: Lens_' CardsChecklistIdChecklistCurrentCheckItem (Maybe Text)
cardsChecklistIdChecklistCurrentCheckItemPosL f CardsChecklistIdChecklistCurrentCheckItem{..} = (\cardsChecklistIdChecklistCurrentCheckItemPos -> CardsChecklistIdChecklistCurrentCheckItem { cardsChecklistIdChecklistCurrentCheckItemPos, ..} ) <$> f cardsChecklistIdChecklistCurrentCheckItemPos
{-# INLINE cardsChecklistIdChecklistCurrentCheckItemPosL #-}

-- | 'cardsChecklistIdChecklistCurrentCheckItemState' Lens
cardsChecklistIdChecklistCurrentCheckItemStateL :: Lens_' CardsChecklistIdChecklistCurrentCheckItem (Maybe Text)
cardsChecklistIdChecklistCurrentCheckItemStateL f CardsChecklistIdChecklistCurrentCheckItem{..} = (\cardsChecklistIdChecklistCurrentCheckItemState -> CardsChecklistIdChecklistCurrentCheckItem { cardsChecklistIdChecklistCurrentCheckItemState, ..} ) <$> f cardsChecklistIdChecklistCurrentCheckItemState
{-# INLINE cardsChecklistIdChecklistCurrentCheckItemStateL #-}



-- * CardsChecklists

-- | 'cardsChecklistsIdChecklistSource' Lens
cardsChecklistsIdChecklistSourceL :: Lens_' CardsChecklists (Maybe Text)
cardsChecklistsIdChecklistSourceL f CardsChecklists{..} = (\cardsChecklistsIdChecklistSource -> CardsChecklists { cardsChecklistsIdChecklistSource, ..} ) <$> f cardsChecklistsIdChecklistSource
{-# INLINE cardsChecklistsIdChecklistSourceL #-}

-- | 'cardsChecklistsName' Lens
cardsChecklistsNameL :: Lens_' CardsChecklists (Maybe Text)
cardsChecklistsNameL f CardsChecklists{..} = (\cardsChecklistsName -> CardsChecklists { cardsChecklistsName, ..} ) <$> f cardsChecklistsName
{-# INLINE cardsChecklistsNameL #-}

-- | 'cardsChecklistsValue' Lens
cardsChecklistsValueL :: Lens_' CardsChecklists (Maybe Text)
cardsChecklistsValueL f CardsChecklists{..} = (\cardsChecklistsValue -> CardsChecklists { cardsChecklistsValue, ..} ) <$> f cardsChecklistsValue
{-# INLINE cardsChecklistsValueL #-}



-- * CardsClosed

-- | 'cardsClosedValue' Lens
cardsClosedValueL :: Lens_' CardsClosed (Maybe Text)
cardsClosedValueL f CardsClosed{..} = (\cardsClosedValue -> CardsClosed { cardsClosedValue, ..} ) <$> f cardsClosedValue
{-# INLINE cardsClosedValueL #-}



-- * CardsDesc

-- | 'cardsDescValue' Lens
cardsDescValueL :: Lens_' CardsDesc (Maybe Text)
cardsDescValueL f CardsDesc{..} = (\cardsDescValue -> CardsDesc { cardsDescValue, ..} ) <$> f cardsDescValue
{-# INLINE cardsDescValueL #-}



-- * CardsDue

-- | 'cardsDueValue' Lens
cardsDueValueL :: Lens_' CardsDue (Maybe Text)
cardsDueValueL f CardsDue{..} = (\cardsDueValue -> CardsDue { cardsDueValue, ..} ) <$> f cardsDueValue
{-# INLINE cardsDueValueL #-}



-- * CardsIdAttachmentCover

-- | 'cardsIdAttachmentCoverValue' Lens
cardsIdAttachmentCoverValueL :: Lens_' CardsIdAttachmentCover (Maybe Text)
cardsIdAttachmentCoverValueL f CardsIdAttachmentCover{..} = (\cardsIdAttachmentCoverValue -> CardsIdAttachmentCover { cardsIdAttachmentCoverValue, ..} ) <$> f cardsIdAttachmentCoverValue
{-# INLINE cardsIdAttachmentCoverValueL #-}



-- * CardsIdBoard

-- | 'cardsIdBoardIdList' Lens
cardsIdBoardIdListL :: Lens_' CardsIdBoard (Maybe Text)
cardsIdBoardIdListL f CardsIdBoard{..} = (\cardsIdBoardIdList -> CardsIdBoard { cardsIdBoardIdList, ..} ) <$> f cardsIdBoardIdList
{-# INLINE cardsIdBoardIdListL #-}

-- | 'cardsIdBoardValue' Lens
cardsIdBoardValueL :: Lens_' CardsIdBoard (Maybe Text)
cardsIdBoardValueL f CardsIdBoard{..} = (\cardsIdBoardValue -> CardsIdBoard { cardsIdBoardValue, ..} ) <$> f cardsIdBoardValue
{-# INLINE cardsIdBoardValueL #-}



-- * CardsIdLabels

-- | 'cardsIdLabelsValue' Lens
cardsIdLabelsValueL :: Lens_' CardsIdLabels (Maybe Text)
cardsIdLabelsValueL f CardsIdLabels{..} = (\cardsIdLabelsValue -> CardsIdLabels { cardsIdLabelsValue, ..} ) <$> f cardsIdLabelsValue
{-# INLINE cardsIdLabelsValueL #-}



-- * CardsIdList

-- | 'cardsIdListValue' Lens
cardsIdListValueL :: Lens_' CardsIdList (Maybe Text)
cardsIdListValueL f CardsIdList{..} = (\cardsIdListValue -> CardsIdList { cardsIdListValue, ..} ) <$> f cardsIdListValue
{-# INLINE cardsIdListValueL #-}



-- * CardsIdMembers

-- | 'cardsIdMembersValue' Lens
cardsIdMembersValueL :: Lens_' CardsIdMembers (Maybe Text)
cardsIdMembersValueL f CardsIdMembers{..} = (\cardsIdMembersValue -> CardsIdMembers { cardsIdMembersValue, ..} ) <$> f cardsIdMembersValue
{-# INLINE cardsIdMembersValueL #-}



-- * CardsLabels

-- | 'cardsLabelsColor' Lens
cardsLabelsColorL :: Lens_' CardsLabels (Maybe Text)
cardsLabelsColorL f CardsLabels{..} = (\cardsLabelsColor -> CardsLabels { cardsLabelsColor, ..} ) <$> f cardsLabelsColor
{-# INLINE cardsLabelsColorL #-}

-- | 'cardsLabelsName' Lens
cardsLabelsNameL :: Lens_' CardsLabels (Maybe Text)
cardsLabelsNameL f CardsLabels{..} = (\cardsLabelsName -> CardsLabels { cardsLabelsName, ..} ) <$> f cardsLabelsName
{-# INLINE cardsLabelsNameL #-}

-- | 'cardsLabelsValue' Lens
cardsLabelsValueL :: Lens_' CardsLabels (Maybe Text)
cardsLabelsValueL f CardsLabels{..} = (\cardsLabelsValue -> CardsLabels { cardsLabelsValue, ..} ) <$> f cardsLabelsValue
{-# INLINE cardsLabelsValueL #-}



-- * CardsMembersVoted

-- | 'cardsMembersVotedValue' Lens
cardsMembersVotedValueL :: Lens_' CardsMembersVoted (Maybe Text)
cardsMembersVotedValueL f CardsMembersVoted{..} = (\cardsMembersVotedValue -> CardsMembersVoted { cardsMembersVotedValue, ..} ) <$> f cardsMembersVotedValue
{-# INLINE cardsMembersVotedValueL #-}



-- * CardsName

-- | 'cardsNameValue' Lens
cardsNameValueL :: Lens_' CardsName (Maybe Text)
cardsNameValueL f CardsName{..} = (\cardsNameValue -> CardsName { cardsNameValue, ..} ) <$> f cardsNameValue
{-# INLINE cardsNameValueL #-}



-- * CardsPos

-- | 'cardsPosValue' Lens
cardsPosValueL :: Lens_' CardsPos (Maybe Text)
cardsPosValueL f CardsPos{..} = (\cardsPosValue -> CardsPos { cardsPosValue, ..} ) <$> f cardsPosValue
{-# INLINE cardsPosValueL #-}



-- * CardsStickers

-- | 'cardsStickersImage' Lens
cardsStickersImageL :: Lens_' CardsStickers (Maybe Text)
cardsStickersImageL f CardsStickers{..} = (\cardsStickersImage -> CardsStickers { cardsStickersImage, ..} ) <$> f cardsStickersImage
{-# INLINE cardsStickersImageL #-}

-- | 'cardsStickersLeft' Lens
cardsStickersLeftL :: Lens_' CardsStickers (Maybe Text)
cardsStickersLeftL f CardsStickers{..} = (\cardsStickersLeft -> CardsStickers { cardsStickersLeft, ..} ) <$> f cardsStickersLeft
{-# INLINE cardsStickersLeftL #-}

-- | 'cardsStickersRotate' Lens
cardsStickersRotateL :: Lens_' CardsStickers (Maybe Text)
cardsStickersRotateL f CardsStickers{..} = (\cardsStickersRotate -> CardsStickers { cardsStickersRotate, ..} ) <$> f cardsStickersRotate
{-# INLINE cardsStickersRotateL #-}

-- | 'cardsStickersTop' Lens
cardsStickersTopL :: Lens_' CardsStickers (Maybe Text)
cardsStickersTopL f CardsStickers{..} = (\cardsStickersTop -> CardsStickers { cardsStickersTop, ..} ) <$> f cardsStickersTop
{-# INLINE cardsStickersTopL #-}

-- | 'cardsStickersZIndex' Lens
cardsStickersZIndexL :: Lens_' CardsStickers (Maybe Text)
cardsStickersZIndexL f CardsStickers{..} = (\cardsStickersZIndex -> CardsStickers { cardsStickersZIndex, ..} ) <$> f cardsStickersZIndex
{-# INLINE cardsStickersZIndexL #-}



-- * CardsSubscribed

-- | 'cardsSubscribedValue' Lens
cardsSubscribedValueL :: Lens_' CardsSubscribed (Maybe Text)
cardsSubscribedValueL f CardsSubscribed{..} = (\cardsSubscribedValue -> CardsSubscribed { cardsSubscribedValue, ..} ) <$> f cardsSubscribedValue
{-# INLINE cardsSubscribedValueL #-}



-- * Checklists

-- | 'checklistsIdBoard' Lens
checklistsIdBoardL :: Lens_' Checklists (Maybe Text)
checklistsIdBoardL f Checklists{..} = (\checklistsIdBoard -> Checklists { checklistsIdBoard, ..} ) <$> f checklistsIdBoard
{-# INLINE checklistsIdBoardL #-}

-- | 'checklistsIdCard' Lens
checklistsIdCardL :: Lens_' Checklists (Maybe Text)
checklistsIdCardL f Checklists{..} = (\checklistsIdCard -> Checklists { checklistsIdCard, ..} ) <$> f checklistsIdCard
{-# INLINE checklistsIdCardL #-}

-- | 'checklistsIdChecklistSource' Lens
checklistsIdChecklistSourceL :: Lens_' Checklists (Maybe Text)
checklistsIdChecklistSourceL f Checklists{..} = (\checklistsIdChecklistSource -> Checklists { checklistsIdChecklistSource, ..} ) <$> f checklistsIdChecklistSource
{-# INLINE checklistsIdChecklistSourceL #-}

-- | 'checklistsName' Lens
checklistsNameL :: Lens_' Checklists (Maybe Text)
checklistsNameL f Checklists{..} = (\checklistsName -> Checklists { checklistsName, ..} ) <$> f checklistsName
{-# INLINE checklistsNameL #-}

-- | 'checklistsPos' Lens
checklistsPosL :: Lens_' Checklists (Maybe Text)
checklistsPosL f Checklists{..} = (\checklistsPos -> Checklists { checklistsPos, ..} ) <$> f checklistsPos
{-# INLINE checklistsPosL #-}



-- * ChecklistsCheckItems

-- | 'checklistsCheckItemsChecked' Lens
checklistsCheckItemsCheckedL :: Lens_' ChecklistsCheckItems (Maybe Text)
checklistsCheckItemsCheckedL f ChecklistsCheckItems{..} = (\checklistsCheckItemsChecked -> ChecklistsCheckItems { checklistsCheckItemsChecked, ..} ) <$> f checklistsCheckItemsChecked
{-# INLINE checklistsCheckItemsCheckedL #-}

-- | 'checklistsCheckItemsName' Lens
checklistsCheckItemsNameL :: Lens_' ChecklistsCheckItems (Maybe Text)
checklistsCheckItemsNameL f ChecklistsCheckItems{..} = (\checklistsCheckItemsName -> ChecklistsCheckItems { checklistsCheckItemsName, ..} ) <$> f checklistsCheckItemsName
{-# INLINE checklistsCheckItemsNameL #-}

-- | 'checklistsCheckItemsPos' Lens
checklistsCheckItemsPosL :: Lens_' ChecklistsCheckItems (Maybe Text)
checklistsCheckItemsPosL f ChecklistsCheckItems{..} = (\checklistsCheckItemsPos -> ChecklistsCheckItems { checklistsCheckItemsPos, ..} ) <$> f checklistsCheckItemsPos
{-# INLINE checklistsCheckItemsPosL #-}



-- * ChecklistsIdCard

-- | 'checklistsIdCardValue' Lens
checklistsIdCardValueL :: Lens_' ChecklistsIdCard (Maybe Text)
checklistsIdCardValueL f ChecklistsIdCard{..} = (\checklistsIdCardValue -> ChecklistsIdCard { checklistsIdCardValue, ..} ) <$> f checklistsIdCardValue
{-# INLINE checklistsIdCardValueL #-}



-- * ChecklistsName

-- | 'checklistsNameValue' Lens
checklistsNameValueL :: Lens_' ChecklistsName (Maybe Text)
checklistsNameValueL f ChecklistsName{..} = (\checklistsNameValue -> ChecklistsName { checklistsNameValue, ..} ) <$> f checklistsNameValue
{-# INLINE checklistsNameValueL #-}



-- * ChecklistsPos

-- | 'checklistsPosValue' Lens
checklistsPosValueL :: Lens_' ChecklistsPos (Maybe Text)
checklistsPosValueL f ChecklistsPos{..} = (\checklistsPosValue -> ChecklistsPos { checklistsPosValue, ..} ) <$> f checklistsPosValue
{-# INLINE checklistsPosValueL #-}



-- * LabelNamesBlue

-- | 'labelNamesBlueValue' Lens
labelNamesBlueValueL :: Lens_' LabelNamesBlue (Maybe Text)
labelNamesBlueValueL f LabelNamesBlue{..} = (\labelNamesBlueValue -> LabelNamesBlue { labelNamesBlueValue, ..} ) <$> f labelNamesBlueValue
{-# INLINE labelNamesBlueValueL #-}



-- * LabelNamesGreen

-- | 'labelNamesGreenValue' Lens
labelNamesGreenValueL :: Lens_' LabelNamesGreen (Maybe Text)
labelNamesGreenValueL f LabelNamesGreen{..} = (\labelNamesGreenValue -> LabelNamesGreen { labelNamesGreenValue, ..} ) <$> f labelNamesGreenValue
{-# INLINE labelNamesGreenValueL #-}



-- * LabelNamesOrange

-- | 'labelNamesOrangeValue' Lens
labelNamesOrangeValueL :: Lens_' LabelNamesOrange (Maybe Text)
labelNamesOrangeValueL f LabelNamesOrange{..} = (\labelNamesOrangeValue -> LabelNamesOrange { labelNamesOrangeValue, ..} ) <$> f labelNamesOrangeValue
{-# INLINE labelNamesOrangeValueL #-}



-- * LabelNamesPurple

-- | 'labelNamesPurpleValue' Lens
labelNamesPurpleValueL :: Lens_' LabelNamesPurple (Maybe Text)
labelNamesPurpleValueL f LabelNamesPurple{..} = (\labelNamesPurpleValue -> LabelNamesPurple { labelNamesPurpleValue, ..} ) <$> f labelNamesPurpleValue
{-# INLINE labelNamesPurpleValueL #-}



-- * LabelNamesRed

-- | 'labelNamesRedValue' Lens
labelNamesRedValueL :: Lens_' LabelNamesRed (Maybe Text)
labelNamesRedValueL f LabelNamesRed{..} = (\labelNamesRedValue -> LabelNamesRed { labelNamesRedValue, ..} ) <$> f labelNamesRedValue
{-# INLINE labelNamesRedValueL #-}



-- * LabelNamesYellow

-- | 'labelNamesYellowValue' Lens
labelNamesYellowValueL :: Lens_' LabelNamesYellow (Maybe Text)
labelNamesYellowValueL f LabelNamesYellow{..} = (\labelNamesYellowValue -> LabelNamesYellow { labelNamesYellowValue, ..} ) <$> f labelNamesYellowValue
{-# INLINE labelNamesYellowValueL #-}



-- * Labels

-- | 'labelsColor' Lens
labelsColorL :: Lens_' Labels (Maybe Text)
labelsColorL f Labels{..} = (\labelsColor -> Labels { labelsColor, ..} ) <$> f labelsColor
{-# INLINE labelsColorL #-}

-- | 'labelsIdBoard' Lens
labelsIdBoardL :: Lens_' Labels (Maybe Text)
labelsIdBoardL f Labels{..} = (\labelsIdBoard -> Labels { labelsIdBoard, ..} ) <$> f labelsIdBoard
{-# INLINE labelsIdBoardL #-}

-- | 'labelsName' Lens
labelsNameL :: Lens_' Labels (Maybe Text)
labelsNameL f Labels{..} = (\labelsName -> Labels { labelsName, ..} ) <$> f labelsName
{-# INLINE labelsNameL #-}



-- * LabelsColor

-- | 'labelsColorValue' Lens
labelsColorValueL :: Lens_' LabelsColor (Maybe Text)
labelsColorValueL f LabelsColor{..} = (\labelsColorValue -> LabelsColor { labelsColorValue, ..} ) <$> f labelsColorValue
{-# INLINE labelsColorValueL #-}



-- * LabelsName

-- | 'labelsNameValue' Lens
labelsNameValueL :: Lens_' LabelsName (Maybe Text)
labelsNameValueL f LabelsName{..} = (\labelsNameValue -> LabelsName { labelsNameValue, ..} ) <$> f labelsNameValue
{-# INLINE labelsNameValueL #-}



-- * Lists

-- | 'listsClosed' Lens
listsClosedL :: Lens_' Lists (Maybe Text)
listsClosedL f Lists{..} = (\listsClosed -> Lists { listsClosed, ..} ) <$> f listsClosed
{-# INLINE listsClosedL #-}

-- | 'listsIdBoard' Lens
listsIdBoardL :: Lens_' Lists (Maybe Text)
listsIdBoardL f Lists{..} = (\listsIdBoard -> Lists { listsIdBoard, ..} ) <$> f listsIdBoard
{-# INLINE listsIdBoardL #-}

-- | 'listsIdListSource' Lens
listsIdListSourceL :: Lens_' Lists (Maybe Text)
listsIdListSourceL f Lists{..} = (\listsIdListSource -> Lists { listsIdListSource, ..} ) <$> f listsIdListSource
{-# INLINE listsIdListSourceL #-}

-- | 'listsName' Lens
listsNameL :: Lens_' Lists (Maybe Text)
listsNameL f Lists{..} = (\listsName -> Lists { listsName, ..} ) <$> f listsName
{-# INLINE listsNameL #-}

-- | 'listsPos' Lens
listsPosL :: Lens_' Lists (Maybe Text)
listsPosL f Lists{..} = (\listsPos -> Lists { listsPos, ..} ) <$> f listsPos
{-# INLINE listsPosL #-}

-- | 'listsSubscribed' Lens
listsSubscribedL :: Lens_' Lists (Maybe Text)
listsSubscribedL f Lists{..} = (\listsSubscribed -> Lists { listsSubscribed, ..} ) <$> f listsSubscribed
{-# INLINE listsSubscribedL #-}



-- * ListsCards

-- | 'listsCardsDesc' Lens
listsCardsDescL :: Lens_' ListsCards (Maybe Text)
listsCardsDescL f ListsCards{..} = (\listsCardsDesc -> ListsCards { listsCardsDesc, ..} ) <$> f listsCardsDesc
{-# INLINE listsCardsDescL #-}

-- | 'listsCardsDue' Lens
listsCardsDueL :: Lens_' ListsCards (Maybe Text)
listsCardsDueL f ListsCards{..} = (\listsCardsDue -> ListsCards { listsCardsDue, ..} ) <$> f listsCardsDue
{-# INLINE listsCardsDueL #-}

-- | 'listsCardsIdMembers' Lens
listsCardsIdMembersL :: Lens_' ListsCards (Maybe Text)
listsCardsIdMembersL f ListsCards{..} = (\listsCardsIdMembers -> ListsCards { listsCardsIdMembers, ..} ) <$> f listsCardsIdMembers
{-# INLINE listsCardsIdMembersL #-}

-- | 'listsCardsLabels' Lens
listsCardsLabelsL :: Lens_' ListsCards (Maybe Text)
listsCardsLabelsL f ListsCards{..} = (\listsCardsLabels -> ListsCards { listsCardsLabels, ..} ) <$> f listsCardsLabels
{-# INLINE listsCardsLabelsL #-}

-- | 'listsCardsName' Lens
listsCardsNameL :: Lens_' ListsCards (Maybe Text)
listsCardsNameL f ListsCards{..} = (\listsCardsName -> ListsCards { listsCardsName, ..} ) <$> f listsCardsName
{-# INLINE listsCardsNameL #-}



-- * ListsClosed

-- | 'listsClosedValue' Lens
listsClosedValueL :: Lens_' ListsClosed (Maybe Text)
listsClosedValueL f ListsClosed{..} = (\listsClosedValue -> ListsClosed { listsClosedValue, ..} ) <$> f listsClosedValue
{-# INLINE listsClosedValueL #-}



-- * ListsIdBoard

-- | 'listsIdBoardPos' Lens
listsIdBoardPosL :: Lens_' ListsIdBoard (Maybe Text)
listsIdBoardPosL f ListsIdBoard{..} = (\listsIdBoardPos -> ListsIdBoard { listsIdBoardPos, ..} ) <$> f listsIdBoardPos
{-# INLINE listsIdBoardPosL #-}

-- | 'listsIdBoardValue' Lens
listsIdBoardValueL :: Lens_' ListsIdBoard (Maybe Text)
listsIdBoardValueL f ListsIdBoard{..} = (\listsIdBoardValue -> ListsIdBoard { listsIdBoardValue, ..} ) <$> f listsIdBoardValue
{-# INLINE listsIdBoardValueL #-}



-- * ListsMoveAllCards

-- | 'listsMoveAllCardsIdBoard' Lens
listsMoveAllCardsIdBoardL :: Lens_' ListsMoveAllCards (Maybe Text)
listsMoveAllCardsIdBoardL f ListsMoveAllCards{..} = (\listsMoveAllCardsIdBoard -> ListsMoveAllCards { listsMoveAllCardsIdBoard, ..} ) <$> f listsMoveAllCardsIdBoard
{-# INLINE listsMoveAllCardsIdBoardL #-}



-- * ListsName

-- | 'listsNameValue' Lens
listsNameValueL :: Lens_' ListsName (Maybe Text)
listsNameValueL f ListsName{..} = (\listsNameValue -> ListsName { listsNameValue, ..} ) <$> f listsNameValue
{-# INLINE listsNameValueL #-}



-- * ListsPos

-- | 'listsPosValue' Lens
listsPosValueL :: Lens_' ListsPos (Maybe Text)
listsPosValueL f ListsPos{..} = (\listsPosValue -> ListsPos { listsPosValue, ..} ) <$> f listsPosValue
{-# INLINE listsPosValueL #-}



-- * ListsSubscribed

-- | 'listsSubscribedValue' Lens
listsSubscribedValueL :: Lens_' ListsSubscribed (Maybe Text)
listsSubscribedValueL f ListsSubscribed{..} = (\listsSubscribedValue -> ListsSubscribed { listsSubscribedValue, ..} ) <$> f listsSubscribedValue
{-# INLINE listsSubscribedValueL #-}



-- * Members

-- | 'membersAvatarSource' Lens
membersAvatarSourceL :: Lens_' Members (Maybe Text)
membersAvatarSourceL f Members{..} = (\membersAvatarSource -> Members { membersAvatarSource, ..} ) <$> f membersAvatarSource
{-# INLINE membersAvatarSourceL #-}

-- | 'membersBio' Lens
membersBioL :: Lens_' Members (Maybe Text)
membersBioL f Members{..} = (\membersBio -> Members { membersBio, ..} ) <$> f membersBio
{-# INLINE membersBioL #-}

-- | 'membersFullName' Lens
membersFullNameL :: Lens_' Members (Maybe Text)
membersFullNameL f Members{..} = (\membersFullName -> Members { membersFullName, ..} ) <$> f membersFullName
{-# INLINE membersFullNameL #-}

-- | 'membersInitials' Lens
membersInitialsL :: Lens_' Members (Maybe Text)
membersInitialsL f Members{..} = (\membersInitials -> Members { membersInitials, ..} ) <$> f membersInitials
{-# INLINE membersInitialsL #-}

-- | 'membersPrefscolorBlind' Lens
membersPrefscolorBlindL :: Lens_' Members (Maybe Text)
membersPrefscolorBlindL f Members{..} = (\membersPrefscolorBlind -> Members { membersPrefscolorBlind, ..} ) <$> f membersPrefscolorBlind
{-# INLINE membersPrefscolorBlindL #-}

-- | 'membersPrefslocale' Lens
membersPrefslocaleL :: Lens_' Members (Maybe Text)
membersPrefslocaleL f Members{..} = (\membersPrefslocale -> Members { membersPrefslocale, ..} ) <$> f membersPrefslocale
{-# INLINE membersPrefslocaleL #-}

-- | 'membersPrefsminutesBetweenSummaries' Lens
membersPrefsminutesBetweenSummariesL :: Lens_' Members (Maybe Text)
membersPrefsminutesBetweenSummariesL f Members{..} = (\membersPrefsminutesBetweenSummaries -> Members { membersPrefsminutesBetweenSummaries, ..} ) <$> f membersPrefsminutesBetweenSummaries
{-# INLINE membersPrefsminutesBetweenSummariesL #-}

-- | 'membersUsername' Lens
membersUsernameL :: Lens_' Members (Maybe Text)
membersUsernameL f Members{..} = (\membersUsername -> Members { membersUsername, ..} ) <$> f membersUsername
{-# INLINE membersUsernameL #-}



-- * MembersAvatar

-- | 'membersAvatarFile' Lens
membersAvatarFileL :: Lens_' MembersAvatar (Maybe Text)
membersAvatarFileL f MembersAvatar{..} = (\membersAvatarFile -> MembersAvatar { membersAvatarFile, ..} ) <$> f membersAvatarFile
{-# INLINE membersAvatarFileL #-}



-- * MembersAvatarSource

-- | 'membersAvatarSourceValue' Lens
membersAvatarSourceValueL :: Lens_' MembersAvatarSource (Maybe Text)
membersAvatarSourceValueL f MembersAvatarSource{..} = (\membersAvatarSourceValue -> MembersAvatarSource { membersAvatarSourceValue, ..} ) <$> f membersAvatarSourceValue
{-# INLINE membersAvatarSourceValueL #-}



-- * MembersBio

-- | 'membersBioValue' Lens
membersBioValueL :: Lens_' MembersBio (Maybe Text)
membersBioValueL f MembersBio{..} = (\membersBioValue -> MembersBio { membersBioValue, ..} ) <$> f membersBioValue
{-# INLINE membersBioValueL #-}



-- * MembersBoardBackgrounds

-- | 'membersBoardBackgroundsBrightness' Lens
membersBoardBackgroundsBrightnessL :: Lens_' MembersBoardBackgrounds (Maybe Text)
membersBoardBackgroundsBrightnessL f MembersBoardBackgrounds{..} = (\membersBoardBackgroundsBrightness -> MembersBoardBackgrounds { membersBoardBackgroundsBrightness, ..} ) <$> f membersBoardBackgroundsBrightness
{-# INLINE membersBoardBackgroundsBrightnessL #-}

-- | 'membersBoardBackgroundsFile' Lens
membersBoardBackgroundsFileL :: Lens_' MembersBoardBackgrounds (Maybe Text)
membersBoardBackgroundsFileL f MembersBoardBackgrounds{..} = (\membersBoardBackgroundsFile -> MembersBoardBackgrounds { membersBoardBackgroundsFile, ..} ) <$> f membersBoardBackgroundsFile
{-# INLINE membersBoardBackgroundsFileL #-}

-- | 'membersBoardBackgroundsTile' Lens
membersBoardBackgroundsTileL :: Lens_' MembersBoardBackgrounds (Maybe Text)
membersBoardBackgroundsTileL f MembersBoardBackgrounds{..} = (\membersBoardBackgroundsTile -> MembersBoardBackgrounds { membersBoardBackgroundsTile, ..} ) <$> f membersBoardBackgroundsTile
{-# INLINE membersBoardBackgroundsTileL #-}



-- * MembersBoardStars

-- | 'membersBoardStarsIdBoard' Lens
membersBoardStarsIdBoardL :: Lens_' MembersBoardStars (Maybe Text)
membersBoardStarsIdBoardL f MembersBoardStars{..} = (\membersBoardStarsIdBoard -> MembersBoardStars { membersBoardStarsIdBoard, ..} ) <$> f membersBoardStarsIdBoard
{-# INLINE membersBoardStarsIdBoardL #-}

-- | 'membersBoardStarsPos' Lens
membersBoardStarsPosL :: Lens_' MembersBoardStars (Maybe Text)
membersBoardStarsPosL f MembersBoardStars{..} = (\membersBoardStarsPos -> MembersBoardStars { membersBoardStarsPos, ..} ) <$> f membersBoardStarsPos
{-# INLINE membersBoardStarsPosL #-}



-- * MembersBoardStarsIdBoard

-- | 'membersBoardStarsIdBoardValue' Lens
membersBoardStarsIdBoardValueL :: Lens_' MembersBoardStarsIdBoard (Maybe Text)
membersBoardStarsIdBoardValueL f MembersBoardStarsIdBoard{..} = (\membersBoardStarsIdBoardValue -> MembersBoardStarsIdBoard { membersBoardStarsIdBoardValue, ..} ) <$> f membersBoardStarsIdBoardValue
{-# INLINE membersBoardStarsIdBoardValueL #-}



-- * MembersBoardStarsPos

-- | 'membersBoardStarsPosValue' Lens
membersBoardStarsPosValueL :: Lens_' MembersBoardStarsPos (Maybe Text)
membersBoardStarsPosValueL f MembersBoardStarsPos{..} = (\membersBoardStarsPosValue -> MembersBoardStarsPos { membersBoardStarsPosValue, ..} ) <$> f membersBoardStarsPosValue
{-# INLINE membersBoardStarsPosValueL #-}



-- * MembersCustomBoardBackgrounds

-- | 'membersCustomBoardBackgroundsBrightness' Lens
membersCustomBoardBackgroundsBrightnessL :: Lens_' MembersCustomBoardBackgrounds (Maybe Text)
membersCustomBoardBackgroundsBrightnessL f MembersCustomBoardBackgrounds{..} = (\membersCustomBoardBackgroundsBrightness -> MembersCustomBoardBackgrounds { membersCustomBoardBackgroundsBrightness, ..} ) <$> f membersCustomBoardBackgroundsBrightness
{-# INLINE membersCustomBoardBackgroundsBrightnessL #-}

-- | 'membersCustomBoardBackgroundsFile' Lens
membersCustomBoardBackgroundsFileL :: Lens_' MembersCustomBoardBackgrounds (Maybe Text)
membersCustomBoardBackgroundsFileL f MembersCustomBoardBackgrounds{..} = (\membersCustomBoardBackgroundsFile -> MembersCustomBoardBackgrounds { membersCustomBoardBackgroundsFile, ..} ) <$> f membersCustomBoardBackgroundsFile
{-# INLINE membersCustomBoardBackgroundsFileL #-}

-- | 'membersCustomBoardBackgroundsTile' Lens
membersCustomBoardBackgroundsTileL :: Lens_' MembersCustomBoardBackgrounds (Maybe Text)
membersCustomBoardBackgroundsTileL f MembersCustomBoardBackgrounds{..} = (\membersCustomBoardBackgroundsTile -> MembersCustomBoardBackgrounds { membersCustomBoardBackgroundsTile, ..} ) <$> f membersCustomBoardBackgroundsTile
{-# INLINE membersCustomBoardBackgroundsTileL #-}



-- * MembersCustomEmoji

-- | 'membersCustomEmojiFile' Lens
membersCustomEmojiFileL :: Lens_' MembersCustomEmoji (Maybe Text)
membersCustomEmojiFileL f MembersCustomEmoji{..} = (\membersCustomEmojiFile -> MembersCustomEmoji { membersCustomEmojiFile, ..} ) <$> f membersCustomEmojiFile
{-# INLINE membersCustomEmojiFileL #-}

-- | 'membersCustomEmojiName' Lens
membersCustomEmojiNameL :: Lens_' MembersCustomEmoji (Maybe Text)
membersCustomEmojiNameL f MembersCustomEmoji{..} = (\membersCustomEmojiName -> MembersCustomEmoji { membersCustomEmojiName, ..} ) <$> f membersCustomEmojiName
{-# INLINE membersCustomEmojiNameL #-}



-- * MembersCustomStickers

-- | 'membersCustomStickersFile' Lens
membersCustomStickersFileL :: Lens_' MembersCustomStickers (Maybe Text)
membersCustomStickersFileL f MembersCustomStickers{..} = (\membersCustomStickersFile -> MembersCustomStickers { membersCustomStickersFile, ..} ) <$> f membersCustomStickersFile
{-# INLINE membersCustomStickersFileL #-}



-- * MembersFullName

-- | 'membersFullNameValue' Lens
membersFullNameValueL :: Lens_' MembersFullName (Maybe Text)
membersFullNameValueL f MembersFullName{..} = (\membersFullNameValue -> MembersFullName { membersFullNameValue, ..} ) <$> f membersFullNameValue
{-# INLINE membersFullNameValueL #-}



-- * MembersInitials

-- | 'membersInitialsValue' Lens
membersInitialsValueL :: Lens_' MembersInitials (Maybe Text)
membersInitialsValueL f MembersInitials{..} = (\membersInitialsValue -> MembersInitials { membersInitialsValue, ..} ) <$> f membersInitialsValue
{-# INLINE membersInitialsValueL #-}



-- * MembersOneTimeMessagesDismissed

-- | 'membersOneTimeMessagesDismissedValue' Lens
membersOneTimeMessagesDismissedValueL :: Lens_' MembersOneTimeMessagesDismissed (Maybe Text)
membersOneTimeMessagesDismissedValueL f MembersOneTimeMessagesDismissed{..} = (\membersOneTimeMessagesDismissedValue -> MembersOneTimeMessagesDismissed { membersOneTimeMessagesDismissedValue, ..} ) <$> f membersOneTimeMessagesDismissedValue
{-# INLINE membersOneTimeMessagesDismissedValueL #-}



-- * MembersSavedSearches

-- | 'membersSavedSearchesName' Lens
membersSavedSearchesNameL :: Lens_' MembersSavedSearches (Maybe Text)
membersSavedSearchesNameL f MembersSavedSearches{..} = (\membersSavedSearchesName -> MembersSavedSearches { membersSavedSearchesName, ..} ) <$> f membersSavedSearchesName
{-# INLINE membersSavedSearchesNameL #-}

-- | 'membersSavedSearchesPos' Lens
membersSavedSearchesPosL :: Lens_' MembersSavedSearches (Maybe Text)
membersSavedSearchesPosL f MembersSavedSearches{..} = (\membersSavedSearchesPos -> MembersSavedSearches { membersSavedSearchesPos, ..} ) <$> f membersSavedSearchesPos
{-# INLINE membersSavedSearchesPosL #-}

-- | 'membersSavedSearchesQuery' Lens
membersSavedSearchesQueryL :: Lens_' MembersSavedSearches (Maybe Text)
membersSavedSearchesQueryL f MembersSavedSearches{..} = (\membersSavedSearchesQuery -> MembersSavedSearches { membersSavedSearchesQuery, ..} ) <$> f membersSavedSearchesQuery
{-# INLINE membersSavedSearchesQueryL #-}



-- * MembersSavedSearchesName

-- | 'membersSavedSearchesNameValue' Lens
membersSavedSearchesNameValueL :: Lens_' MembersSavedSearchesName (Maybe Text)
membersSavedSearchesNameValueL f MembersSavedSearchesName{..} = (\membersSavedSearchesNameValue -> MembersSavedSearchesName { membersSavedSearchesNameValue, ..} ) <$> f membersSavedSearchesNameValue
{-# INLINE membersSavedSearchesNameValueL #-}



-- * MembersSavedSearchesPos

-- | 'membersSavedSearchesPosValue' Lens
membersSavedSearchesPosValueL :: Lens_' MembersSavedSearchesPos (Maybe Text)
membersSavedSearchesPosValueL f MembersSavedSearchesPos{..} = (\membersSavedSearchesPosValue -> MembersSavedSearchesPos { membersSavedSearchesPosValue, ..} ) <$> f membersSavedSearchesPosValue
{-# INLINE membersSavedSearchesPosValueL #-}



-- * MembersSavedSearchesQuery

-- | 'membersSavedSearchesQueryValue' Lens
membersSavedSearchesQueryValueL :: Lens_' MembersSavedSearchesQuery (Maybe Text)
membersSavedSearchesQueryValueL f MembersSavedSearchesQuery{..} = (\membersSavedSearchesQueryValue -> MembersSavedSearchesQuery { membersSavedSearchesQueryValue, ..} ) <$> f membersSavedSearchesQueryValue
{-# INLINE membersSavedSearchesQueryValueL #-}



-- * MembersUsername

-- | 'membersUsernameValue' Lens
membersUsernameValueL :: Lens_' MembersUsername (Maybe Text)
membersUsernameValueL f MembersUsername{..} = (\membersUsernameValue -> MembersUsername { membersUsernameValue, ..} ) <$> f membersUsernameValue
{-# INLINE membersUsernameValueL #-}



-- * MyPrefsEmailPosition

-- | 'myPrefsEmailPositionValue' Lens
myPrefsEmailPositionValueL :: Lens_' MyPrefsEmailPosition (Maybe Text)
myPrefsEmailPositionValueL f MyPrefsEmailPosition{..} = (\myPrefsEmailPositionValue -> MyPrefsEmailPosition { myPrefsEmailPositionValue, ..} ) <$> f myPrefsEmailPositionValue
{-# INLINE myPrefsEmailPositionValueL #-}



-- * MyPrefsIdEmailList

-- | 'myPrefsIdEmailListValue' Lens
myPrefsIdEmailListValueL :: Lens_' MyPrefsIdEmailList (Maybe Text)
myPrefsIdEmailListValueL f MyPrefsIdEmailList{..} = (\myPrefsIdEmailListValue -> MyPrefsIdEmailList { myPrefsIdEmailListValue, ..} ) <$> f myPrefsIdEmailListValue
{-# INLINE myPrefsIdEmailListValueL #-}



-- * MyPrefsShowListGuide

-- | 'myPrefsShowListGuideValue' Lens
myPrefsShowListGuideValueL :: Lens_' MyPrefsShowListGuide (Maybe Text)
myPrefsShowListGuideValueL f MyPrefsShowListGuide{..} = (\myPrefsShowListGuideValue -> MyPrefsShowListGuide { myPrefsShowListGuideValue, ..} ) <$> f myPrefsShowListGuideValue
{-# INLINE myPrefsShowListGuideValueL #-}



-- * MyPrefsShowSidebar

-- | 'myPrefsShowSidebarValue' Lens
myPrefsShowSidebarValueL :: Lens_' MyPrefsShowSidebar (Maybe Text)
myPrefsShowSidebarValueL f MyPrefsShowSidebar{..} = (\myPrefsShowSidebarValue -> MyPrefsShowSidebar { myPrefsShowSidebarValue, ..} ) <$> f myPrefsShowSidebarValue
{-# INLINE myPrefsShowSidebarValueL #-}



-- * MyPrefsShowSidebarActivity

-- | 'myPrefsShowSidebarActivityValue' Lens
myPrefsShowSidebarActivityValueL :: Lens_' MyPrefsShowSidebarActivity (Maybe Text)
myPrefsShowSidebarActivityValueL f MyPrefsShowSidebarActivity{..} = (\myPrefsShowSidebarActivityValue -> MyPrefsShowSidebarActivity { myPrefsShowSidebarActivityValue, ..} ) <$> f myPrefsShowSidebarActivityValue
{-# INLINE myPrefsShowSidebarActivityValueL #-}



-- * MyPrefsShowSidebarBoardActions

-- | 'myPrefsShowSidebarBoardActionsValue' Lens
myPrefsShowSidebarBoardActionsValueL :: Lens_' MyPrefsShowSidebarBoardActions (Maybe Text)
myPrefsShowSidebarBoardActionsValueL f MyPrefsShowSidebarBoardActions{..} = (\myPrefsShowSidebarBoardActionsValue -> MyPrefsShowSidebarBoardActions { myPrefsShowSidebarBoardActionsValue, ..} ) <$> f myPrefsShowSidebarBoardActionsValue
{-# INLINE myPrefsShowSidebarBoardActionsValueL #-}



-- * MyPrefsShowSidebarMembers

-- | 'myPrefsShowSidebarMembersValue' Lens
myPrefsShowSidebarMembersValueL :: Lens_' MyPrefsShowSidebarMembers (Maybe Text)
myPrefsShowSidebarMembersValueL f MyPrefsShowSidebarMembers{..} = (\myPrefsShowSidebarMembersValue -> MyPrefsShowSidebarMembers { myPrefsShowSidebarMembersValue, ..} ) <$> f myPrefsShowSidebarMembersValue
{-# INLINE myPrefsShowSidebarMembersValueL #-}



-- * Notifications

-- | 'notificationsUnread' Lens
notificationsUnreadL :: Lens_' Notifications (Maybe Text)
notificationsUnreadL f Notifications{..} = (\notificationsUnread -> Notifications { notificationsUnread, ..} ) <$> f notificationsUnread
{-# INLINE notificationsUnreadL #-}



-- * NotificationsUnread

-- | 'notificationsUnreadValue' Lens
notificationsUnreadValueL :: Lens_' NotificationsUnread (Maybe Text)
notificationsUnreadValueL f NotificationsUnread{..} = (\notificationsUnreadValue -> NotificationsUnread { notificationsUnreadValue, ..} ) <$> f notificationsUnreadValue
{-# INLINE notificationsUnreadValueL #-}



-- * Organizations

-- | 'organizationsDesc' Lens
organizationsDescL :: Lens_' Organizations (Maybe Text)
organizationsDescL f Organizations{..} = (\organizationsDesc -> Organizations { organizationsDesc, ..} ) <$> f organizationsDesc
{-# INLINE organizationsDescL #-}

-- | 'organizationsDisplayName' Lens
organizationsDisplayNameL :: Lens_' Organizations (Maybe Text)
organizationsDisplayNameL f Organizations{..} = (\organizationsDisplayName -> Organizations { organizationsDisplayName, ..} ) <$> f organizationsDisplayName
{-# INLINE organizationsDisplayNameL #-}

-- | 'organizationsName' Lens
organizationsNameL :: Lens_' Organizations (Maybe Text)
organizationsNameL f Organizations{..} = (\organizationsName -> Organizations { organizationsName, ..} ) <$> f organizationsName
{-# INLINE organizationsNameL #-}

-- | 'organizationsPrefsassociatedDomain' Lens
organizationsPrefsassociatedDomainL :: Lens_' Organizations (Maybe Text)
organizationsPrefsassociatedDomainL f Organizations{..} = (\organizationsPrefsassociatedDomain -> Organizations { organizationsPrefsassociatedDomain, ..} ) <$> f organizationsPrefsassociatedDomain
{-# INLINE organizationsPrefsassociatedDomainL #-}

-- | 'organizationsPrefsboardVisibilityRestrictorg' Lens
organizationsPrefsboardVisibilityRestrictorgL :: Lens_' Organizations (Maybe Text)
organizationsPrefsboardVisibilityRestrictorgL f Organizations{..} = (\organizationsPrefsboardVisibilityRestrictorg -> Organizations { organizationsPrefsboardVisibilityRestrictorg, ..} ) <$> f organizationsPrefsboardVisibilityRestrictorg
{-# INLINE organizationsPrefsboardVisibilityRestrictorgL #-}

-- | 'organizationsPrefsboardVisibilityRestrictprivate' Lens
organizationsPrefsboardVisibilityRestrictprivateL :: Lens_' Organizations (Maybe Text)
organizationsPrefsboardVisibilityRestrictprivateL f Organizations{..} = (\organizationsPrefsboardVisibilityRestrictprivate -> Organizations { organizationsPrefsboardVisibilityRestrictprivate, ..} ) <$> f organizationsPrefsboardVisibilityRestrictprivate
{-# INLINE organizationsPrefsboardVisibilityRestrictprivateL #-}

-- | 'organizationsPrefsboardVisibilityRestrictpublic' Lens
organizationsPrefsboardVisibilityRestrictpublicL :: Lens_' Organizations (Maybe Text)
organizationsPrefsboardVisibilityRestrictpublicL f Organizations{..} = (\organizationsPrefsboardVisibilityRestrictpublic -> Organizations { organizationsPrefsboardVisibilityRestrictpublic, ..} ) <$> f organizationsPrefsboardVisibilityRestrictpublic
{-# INLINE organizationsPrefsboardVisibilityRestrictpublicL #-}

-- | 'organizationsPrefsexternalMembersDisabled' Lens
organizationsPrefsexternalMembersDisabledL :: Lens_' Organizations (Maybe Text)
organizationsPrefsexternalMembersDisabledL f Organizations{..} = (\organizationsPrefsexternalMembersDisabled -> Organizations { organizationsPrefsexternalMembersDisabled, ..} ) <$> f organizationsPrefsexternalMembersDisabled
{-# INLINE organizationsPrefsexternalMembersDisabledL #-}

-- | 'organizationsPrefsgoogleAppsVersion' Lens
organizationsPrefsgoogleAppsVersionL :: Lens_' Organizations (Maybe Text)
organizationsPrefsgoogleAppsVersionL f Organizations{..} = (\organizationsPrefsgoogleAppsVersion -> Organizations { organizationsPrefsgoogleAppsVersion, ..} ) <$> f organizationsPrefsgoogleAppsVersion
{-# INLINE organizationsPrefsgoogleAppsVersionL #-}

-- | 'organizationsPrefsorgInviteRestrict' Lens
organizationsPrefsorgInviteRestrictL :: Lens_' Organizations (Maybe Text)
organizationsPrefsorgInviteRestrictL f Organizations{..} = (\organizationsPrefsorgInviteRestrict -> Organizations { organizationsPrefsorgInviteRestrict, ..} ) <$> f organizationsPrefsorgInviteRestrict
{-# INLINE organizationsPrefsorgInviteRestrictL #-}

-- | 'organizationsPrefspermissionLevel' Lens
organizationsPrefspermissionLevelL :: Lens_' Organizations (Maybe Text)
organizationsPrefspermissionLevelL f Organizations{..} = (\organizationsPrefspermissionLevel -> Organizations { organizationsPrefspermissionLevel, ..} ) <$> f organizationsPrefspermissionLevel
{-# INLINE organizationsPrefspermissionLevelL #-}

-- | 'organizationsWebsite' Lens
organizationsWebsiteL :: Lens_' Organizations (Maybe Text)
organizationsWebsiteL f Organizations{..} = (\organizationsWebsite -> Organizations { organizationsWebsite, ..} ) <$> f organizationsWebsite
{-# INLINE organizationsWebsiteL #-}



-- * OrganizationsDesc

-- | 'organizationsDescValue' Lens
organizationsDescValueL :: Lens_' OrganizationsDesc (Maybe Text)
organizationsDescValueL f OrganizationsDesc{..} = (\organizationsDescValue -> OrganizationsDesc { organizationsDescValue, ..} ) <$> f organizationsDescValue
{-# INLINE organizationsDescValueL #-}



-- * OrganizationsDisplayName

-- | 'organizationsDisplayNameValue' Lens
organizationsDisplayNameValueL :: Lens_' OrganizationsDisplayName (Maybe Text)
organizationsDisplayNameValueL f OrganizationsDisplayName{..} = (\organizationsDisplayNameValue -> OrganizationsDisplayName { organizationsDisplayNameValue, ..} ) <$> f organizationsDisplayNameValue
{-# INLINE organizationsDisplayNameValueL #-}



-- * OrganizationsLogo

-- | 'organizationsLogoFile' Lens
organizationsLogoFileL :: Lens_' OrganizationsLogo (Maybe Text)
organizationsLogoFileL f OrganizationsLogo{..} = (\organizationsLogoFile -> OrganizationsLogo { organizationsLogoFile, ..} ) <$> f organizationsLogoFile
{-# INLINE organizationsLogoFileL #-}



-- * OrganizationsMembers

-- | 'organizationsMembersEmail' Lens
organizationsMembersEmailL :: Lens_' OrganizationsMembers (Maybe Text)
organizationsMembersEmailL f OrganizationsMembers{..} = (\organizationsMembersEmail -> OrganizationsMembers { organizationsMembersEmail, ..} ) <$> f organizationsMembersEmail
{-# INLINE organizationsMembersEmailL #-}

-- | 'organizationsMembersFullName' Lens
organizationsMembersFullNameL :: Lens_' OrganizationsMembers (Maybe Text)
organizationsMembersFullNameL f OrganizationsMembers{..} = (\organizationsMembersFullName -> OrganizationsMembers { organizationsMembersFullName, ..} ) <$> f organizationsMembersFullName
{-# INLINE organizationsMembersFullNameL #-}

-- | 'organizationsMembersType' Lens
organizationsMembersTypeL :: Lens_' OrganizationsMembers (Maybe Text)
organizationsMembersTypeL f OrganizationsMembers{..} = (\organizationsMembersType -> OrganizationsMembers { organizationsMembersType, ..} ) <$> f organizationsMembersType
{-# INLINE organizationsMembersTypeL #-}



-- * OrganizationsMembersDeactivated

-- | 'organizationsMembersDeactivatedValue' Lens
organizationsMembersDeactivatedValueL :: Lens_' OrganizationsMembersDeactivated (Maybe Text)
organizationsMembersDeactivatedValueL f OrganizationsMembersDeactivated{..} = (\organizationsMembersDeactivatedValue -> OrganizationsMembersDeactivated { organizationsMembersDeactivatedValue, ..} ) <$> f organizationsMembersDeactivatedValue
{-# INLINE organizationsMembersDeactivatedValueL #-}



-- * OrganizationsMemberships

-- | 'organizationsMembershipsMemberFields' Lens
organizationsMembershipsMemberFieldsL :: Lens_' OrganizationsMemberships (Maybe Text)
organizationsMembershipsMemberFieldsL f OrganizationsMemberships{..} = (\organizationsMembershipsMemberFields -> OrganizationsMemberships { organizationsMembershipsMemberFields, ..} ) <$> f organizationsMembershipsMemberFields
{-# INLINE organizationsMembershipsMemberFieldsL #-}

-- | 'organizationsMembershipsType' Lens
organizationsMembershipsTypeL :: Lens_' OrganizationsMemberships (Maybe Text)
organizationsMembershipsTypeL f OrganizationsMemberships{..} = (\organizationsMembershipsType -> OrganizationsMemberships { organizationsMembershipsType, ..} ) <$> f organizationsMembershipsType
{-# INLINE organizationsMembershipsTypeL #-}



-- * OrganizationsName

-- | 'organizationsNameValue' Lens
organizationsNameValueL :: Lens_' OrganizationsName (Maybe Text)
organizationsNameValueL f OrganizationsName{..} = (\organizationsNameValue -> OrganizationsName { organizationsNameValue, ..} ) <$> f organizationsNameValue
{-# INLINE organizationsNameValueL #-}



-- * OrganizationsWebsite

-- | 'organizationsWebsiteValue' Lens
organizationsWebsiteValueL :: Lens_' OrganizationsWebsite (Maybe Text)
organizationsWebsiteValueL f OrganizationsWebsite{..} = (\organizationsWebsiteValue -> OrganizationsWebsite { organizationsWebsiteValue, ..} ) <$> f organizationsWebsiteValue
{-# INLINE organizationsWebsiteValueL #-}



-- * PrefsAssociatedDomain

-- | 'prefsAssociatedDomainValue' Lens
prefsAssociatedDomainValueL :: Lens_' PrefsAssociatedDomain (Maybe Text)
prefsAssociatedDomainValueL f PrefsAssociatedDomain{..} = (\prefsAssociatedDomainValue -> PrefsAssociatedDomain { prefsAssociatedDomainValue, ..} ) <$> f prefsAssociatedDomainValue
{-# INLINE prefsAssociatedDomainValueL #-}



-- * PrefsBackground

-- | 'prefsBackgroundValue' Lens
prefsBackgroundValueL :: Lens_' PrefsBackground (Maybe Text)
prefsBackgroundValueL f PrefsBackground{..} = (\prefsBackgroundValue -> PrefsBackground { prefsBackgroundValue, ..} ) <$> f prefsBackgroundValue
{-# INLINE prefsBackgroundValueL #-}



-- * PrefsBoardVisibilityRestrict

-- | 'prefsBoardVisibilityRestrictValue' Lens
prefsBoardVisibilityRestrictValueL :: Lens_' PrefsBoardVisibilityRestrict (Maybe Text)
prefsBoardVisibilityRestrictValueL f PrefsBoardVisibilityRestrict{..} = (\prefsBoardVisibilityRestrictValue -> PrefsBoardVisibilityRestrict { prefsBoardVisibilityRestrictValue, ..} ) <$> f prefsBoardVisibilityRestrictValue
{-# INLINE prefsBoardVisibilityRestrictValueL #-}



-- * PrefsCalendarFeedEnabled

-- | 'prefsCalendarFeedEnabledValue' Lens
prefsCalendarFeedEnabledValueL :: Lens_' PrefsCalendarFeedEnabled (Maybe Text)
prefsCalendarFeedEnabledValueL f PrefsCalendarFeedEnabled{..} = (\prefsCalendarFeedEnabledValue -> PrefsCalendarFeedEnabled { prefsCalendarFeedEnabledValue, ..} ) <$> f prefsCalendarFeedEnabledValue
{-# INLINE prefsCalendarFeedEnabledValueL #-}



-- * PrefsCardAging

-- | 'prefsCardAgingValue' Lens
prefsCardAgingValueL :: Lens_' PrefsCardAging (Maybe Text)
prefsCardAgingValueL f PrefsCardAging{..} = (\prefsCardAgingValue -> PrefsCardAging { prefsCardAgingValue, ..} ) <$> f prefsCardAgingValue
{-# INLINE prefsCardAgingValueL #-}



-- * PrefsCardCovers

-- | 'prefsCardCoversValue' Lens
prefsCardCoversValueL :: Lens_' PrefsCardCovers (Maybe Text)
prefsCardCoversValueL f PrefsCardCovers{..} = (\prefsCardCoversValue -> PrefsCardCovers { prefsCardCoversValue, ..} ) <$> f prefsCardCoversValue
{-# INLINE prefsCardCoversValueL #-}



-- * PrefsColorBlind

-- | 'prefsColorBlindValue' Lens
prefsColorBlindValueL :: Lens_' PrefsColorBlind (Maybe Text)
prefsColorBlindValueL f PrefsColorBlind{..} = (\prefsColorBlindValue -> PrefsColorBlind { prefsColorBlindValue, ..} ) <$> f prefsColorBlindValue
{-# INLINE prefsColorBlindValueL #-}



-- * PrefsComments

-- | 'prefsCommentsValue' Lens
prefsCommentsValueL :: Lens_' PrefsComments (Maybe Text)
prefsCommentsValueL f PrefsComments{..} = (\prefsCommentsValue -> PrefsComments { prefsCommentsValue, ..} ) <$> f prefsCommentsValue
{-# INLINE prefsCommentsValueL #-}



-- * PrefsExternalMembersDisabled

-- | 'prefsExternalMembersDisabledValue' Lens
prefsExternalMembersDisabledValueL :: Lens_' PrefsExternalMembersDisabled (Maybe Text)
prefsExternalMembersDisabledValueL f PrefsExternalMembersDisabled{..} = (\prefsExternalMembersDisabledValue -> PrefsExternalMembersDisabled { prefsExternalMembersDisabledValue, ..} ) <$> f prefsExternalMembersDisabledValue
{-# INLINE prefsExternalMembersDisabledValueL #-}



-- * PrefsGoogleAppsVersion

-- | 'prefsGoogleAppsVersionValue' Lens
prefsGoogleAppsVersionValueL :: Lens_' PrefsGoogleAppsVersion (Maybe Text)
prefsGoogleAppsVersionValueL f PrefsGoogleAppsVersion{..} = (\prefsGoogleAppsVersionValue -> PrefsGoogleAppsVersion { prefsGoogleAppsVersionValue, ..} ) <$> f prefsGoogleAppsVersionValue
{-# INLINE prefsGoogleAppsVersionValueL #-}



-- * PrefsInvitations

-- | 'prefsInvitationsValue' Lens
prefsInvitationsValueL :: Lens_' PrefsInvitations (Maybe Text)
prefsInvitationsValueL f PrefsInvitations{..} = (\prefsInvitationsValue -> PrefsInvitations { prefsInvitationsValue, ..} ) <$> f prefsInvitationsValue
{-# INLINE prefsInvitationsValueL #-}



-- * PrefsLocale

-- | 'prefsLocaleValue' Lens
prefsLocaleValueL :: Lens_' PrefsLocale (Maybe Text)
prefsLocaleValueL f PrefsLocale{..} = (\prefsLocaleValue -> PrefsLocale { prefsLocaleValue, ..} ) <$> f prefsLocaleValue
{-# INLINE prefsLocaleValueL #-}



-- * PrefsMinutesBetweenSummaries

-- | 'prefsMinutesBetweenSummariesValue' Lens
prefsMinutesBetweenSummariesValueL :: Lens_' PrefsMinutesBetweenSummaries (Maybe Text)
prefsMinutesBetweenSummariesValueL f PrefsMinutesBetweenSummaries{..} = (\prefsMinutesBetweenSummariesValue -> PrefsMinutesBetweenSummaries { prefsMinutesBetweenSummariesValue, ..} ) <$> f prefsMinutesBetweenSummariesValue
{-# INLINE prefsMinutesBetweenSummariesValueL #-}



-- * PrefsOrgInviteRestrict

-- | 'prefsOrgInviteRestrictValue' Lens
prefsOrgInviteRestrictValueL :: Lens_' PrefsOrgInviteRestrict (Maybe Text)
prefsOrgInviteRestrictValueL f PrefsOrgInviteRestrict{..} = (\prefsOrgInviteRestrictValue -> PrefsOrgInviteRestrict { prefsOrgInviteRestrictValue, ..} ) <$> f prefsOrgInviteRestrictValue
{-# INLINE prefsOrgInviteRestrictValueL #-}



-- * PrefsPermissionLevel

-- | 'prefsPermissionLevelValue' Lens
prefsPermissionLevelValueL :: Lens_' PrefsPermissionLevel (Maybe Text)
prefsPermissionLevelValueL f PrefsPermissionLevel{..} = (\prefsPermissionLevelValue -> PrefsPermissionLevel { prefsPermissionLevelValue, ..} ) <$> f prefsPermissionLevelValue
{-# INLINE prefsPermissionLevelValueL #-}



-- * PrefsSelfJoin

-- | 'prefsSelfJoinValue' Lens
prefsSelfJoinValueL :: Lens_' PrefsSelfJoin (Maybe Text)
prefsSelfJoinValueL f PrefsSelfJoin{..} = (\prefsSelfJoinValue -> PrefsSelfJoin { prefsSelfJoinValue, ..} ) <$> f prefsSelfJoinValue
{-# INLINE prefsSelfJoinValueL #-}



-- * PrefsVoting

-- | 'prefsVotingValue' Lens
prefsVotingValueL :: Lens_' PrefsVoting (Maybe Text)
prefsVotingValueL f PrefsVoting{..} = (\prefsVotingValue -> PrefsVoting { prefsVotingValue, ..} ) <$> f prefsVotingValue
{-# INLINE prefsVotingValueL #-}



-- * Sessions

-- | 'sessionsIdBoard' Lens
sessionsIdBoardL :: Lens_' Sessions (Maybe Text)
sessionsIdBoardL f Sessions{..} = (\sessionsIdBoard -> Sessions { sessionsIdBoard, ..} ) <$> f sessionsIdBoard
{-# INLINE sessionsIdBoardL #-}

-- | 'sessionsStatus' Lens
sessionsStatusL :: Lens_' Sessions (Maybe Text)
sessionsStatusL f Sessions{..} = (\sessionsStatus -> Sessions { sessionsStatus, ..} ) <$> f sessionsStatus
{-# INLINE sessionsStatusL #-}



-- * SessionsStatus

-- | 'sessionsStatusValue' Lens
sessionsStatusValueL :: Lens_' SessionsStatus (Maybe Text)
sessionsStatusValueL f SessionsStatus{..} = (\sessionsStatusValue -> SessionsStatus { sessionsStatusValue, ..} ) <$> f sessionsStatusValue
{-# INLINE sessionsStatusValueL #-}



-- * TokensWebhooks

-- | 'tokensWebhooksCallbackUrl' Lens
tokensWebhooksCallbackUrlL :: Lens_' TokensWebhooks (Maybe Text)
tokensWebhooksCallbackUrlL f TokensWebhooks{..} = (\tokensWebhooksCallbackUrl -> TokensWebhooks { tokensWebhooksCallbackUrl, ..} ) <$> f tokensWebhooksCallbackUrl
{-# INLINE tokensWebhooksCallbackUrlL #-}

-- | 'tokensWebhooksDescription' Lens
tokensWebhooksDescriptionL :: Lens_' TokensWebhooks (Maybe Text)
tokensWebhooksDescriptionL f TokensWebhooks{..} = (\tokensWebhooksDescription -> TokensWebhooks { tokensWebhooksDescription, ..} ) <$> f tokensWebhooksDescription
{-# INLINE tokensWebhooksDescriptionL #-}

-- | 'tokensWebhooksIdModel' Lens
tokensWebhooksIdModelL :: Lens_' TokensWebhooks (Maybe Text)
tokensWebhooksIdModelL f TokensWebhooks{..} = (\tokensWebhooksIdModel -> TokensWebhooks { tokensWebhooksIdModel, ..} ) <$> f tokensWebhooksIdModel
{-# INLINE tokensWebhooksIdModelL #-}



-- * Webhooks

-- | 'webhooksActive' Lens
webhooksActiveL :: Lens_' Webhooks (Maybe Text)
webhooksActiveL f Webhooks{..} = (\webhooksActive -> Webhooks { webhooksActive, ..} ) <$> f webhooksActive
{-# INLINE webhooksActiveL #-}

-- | 'webhooksCallbackUrl' Lens
webhooksCallbackUrlL :: Lens_' Webhooks (Maybe Text)
webhooksCallbackUrlL f Webhooks{..} = (\webhooksCallbackUrl -> Webhooks { webhooksCallbackUrl, ..} ) <$> f webhooksCallbackUrl
{-# INLINE webhooksCallbackUrlL #-}

-- | 'webhooksDescription' Lens
webhooksDescriptionL :: Lens_' Webhooks (Maybe Text)
webhooksDescriptionL f Webhooks{..} = (\webhooksDescription -> Webhooks { webhooksDescription, ..} ) <$> f webhooksDescription
{-# INLINE webhooksDescriptionL #-}

-- | 'webhooksIdModel' Lens
webhooksIdModelL :: Lens_' Webhooks (Maybe Text)
webhooksIdModelL f Webhooks{..} = (\webhooksIdModel -> Webhooks { webhooksIdModel, ..} ) <$> f webhooksIdModel
{-# INLINE webhooksIdModelL #-}



-- * WebhooksActive

-- | 'webhooksActiveValue' Lens
webhooksActiveValueL :: Lens_' WebhooksActive (Maybe Text)
webhooksActiveValueL f WebhooksActive{..} = (\webhooksActiveValue -> WebhooksActive { webhooksActiveValue, ..} ) <$> f webhooksActiveValue
{-# INLINE webhooksActiveValueL #-}



-- * WebhooksCallbackURL

-- | 'webhooksCallbackURLValue' Lens
webhooksCallbackURLValueL :: Lens_' WebhooksCallbackURL (Maybe Text)
webhooksCallbackURLValueL f WebhooksCallbackURL{..} = (\webhooksCallbackURLValue -> WebhooksCallbackURL { webhooksCallbackURLValue, ..} ) <$> f webhooksCallbackURLValue
{-# INLINE webhooksCallbackURLValueL #-}



-- * WebhooksDescription

-- | 'webhooksDescriptionValue' Lens
webhooksDescriptionValueL :: Lens_' WebhooksDescription (Maybe Text)
webhooksDescriptionValueL f WebhooksDescription{..} = (\webhooksDescriptionValue -> WebhooksDescription { webhooksDescriptionValue, ..} ) <$> f webhooksDescriptionValue
{-# INLINE webhooksDescriptionValueL #-}



-- * WebhooksIdModel

-- | 'webhooksIdModelValue' Lens
webhooksIdModelValueL :: Lens_' WebhooksIdModel (Maybe Text)
webhooksIdModelValueL f WebhooksIdModel{..} = (\webhooksIdModelValue -> WebhooksIdModel { webhooksIdModelValue, ..} ) <$> f webhooksIdModelValue
{-# INLINE webhooksIdModelValueL #-}


