{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import Trello.Model
import Trello.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 5) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy Actions)
      propMimeEq MimeJSON (Proxy :: Proxy ActionsComments)
      propMimeEq MimeJSON (Proxy :: Proxy ActionsText)
      propMimeEq MimeJSON (Proxy :: Proxy Boards)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsChecklists)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsClosed)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsDesc)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsIdOrganization)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsLabels)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsLists)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsMembers)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsMemberships)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsName)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsPowerUps)
      propMimeEq MimeJSON (Proxy :: Proxy BoardsSubscribed)
      propMimeEq MimeJSON (Proxy :: Proxy Cards)
      propMimeEq MimeJSON (Proxy :: Proxy CardsActionsComments)
      propMimeEq MimeJSON (Proxy :: Proxy CardsAttachments)
      propMimeEq MimeJSON (Proxy :: Proxy CardsChecklistCheckItem)
      propMimeEq MimeJSON (Proxy :: Proxy CardsChecklistCheckItemName)
      propMimeEq MimeJSON (Proxy :: Proxy CardsChecklistCheckItemPos)
      propMimeEq MimeJSON (Proxy :: Proxy CardsChecklistCheckItemState)
      propMimeEq MimeJSON (Proxy :: Proxy CardsChecklistIdChecklistCurrentCheckItem)
      propMimeEq MimeJSON (Proxy :: Proxy CardsChecklists)
      propMimeEq MimeJSON (Proxy :: Proxy CardsClosed)
      propMimeEq MimeJSON (Proxy :: Proxy CardsDesc)
      propMimeEq MimeJSON (Proxy :: Proxy CardsDue)
      propMimeEq MimeJSON (Proxy :: Proxy CardsIdAttachmentCover)
      propMimeEq MimeJSON (Proxy :: Proxy CardsIdBoard)
      propMimeEq MimeJSON (Proxy :: Proxy CardsIdLabels)
      propMimeEq MimeJSON (Proxy :: Proxy CardsIdList)
      propMimeEq MimeJSON (Proxy :: Proxy CardsIdMembers)
      propMimeEq MimeJSON (Proxy :: Proxy CardsLabels)
      propMimeEq MimeJSON (Proxy :: Proxy CardsMembersVoted)
      propMimeEq MimeJSON (Proxy :: Proxy CardsName)
      propMimeEq MimeJSON (Proxy :: Proxy CardsPos)
      propMimeEq MimeJSON (Proxy :: Proxy CardsStickers)
      propMimeEq MimeJSON (Proxy :: Proxy CardsSubscribed)
      propMimeEq MimeJSON (Proxy :: Proxy Checklists)
      propMimeEq MimeJSON (Proxy :: Proxy ChecklistsCheckItems)
      propMimeEq MimeJSON (Proxy :: Proxy ChecklistsIdCard)
      propMimeEq MimeJSON (Proxy :: Proxy ChecklistsName)
      propMimeEq MimeJSON (Proxy :: Proxy ChecklistsPos)
      propMimeEq MimeJSON (Proxy :: Proxy LabelNamesBlue)
      propMimeEq MimeJSON (Proxy :: Proxy LabelNamesGreen)
      propMimeEq MimeJSON (Proxy :: Proxy LabelNamesOrange)
      propMimeEq MimeJSON (Proxy :: Proxy LabelNamesPurple)
      propMimeEq MimeJSON (Proxy :: Proxy LabelNamesRed)
      propMimeEq MimeJSON (Proxy :: Proxy LabelNamesYellow)
      propMimeEq MimeJSON (Proxy :: Proxy Labels)
      propMimeEq MimeJSON (Proxy :: Proxy LabelsColor)
      propMimeEq MimeJSON (Proxy :: Proxy LabelsName)
      propMimeEq MimeJSON (Proxy :: Proxy Lists)
      propMimeEq MimeJSON (Proxy :: Proxy ListsCards)
      propMimeEq MimeJSON (Proxy :: Proxy ListsClosed)
      propMimeEq MimeJSON (Proxy :: Proxy ListsIdBoard)
      propMimeEq MimeJSON (Proxy :: Proxy ListsMoveAllCards)
      propMimeEq MimeJSON (Proxy :: Proxy ListsName)
      propMimeEq MimeJSON (Proxy :: Proxy ListsPos)
      propMimeEq MimeJSON (Proxy :: Proxy ListsSubscribed)
      propMimeEq MimeJSON (Proxy :: Proxy Members)
      propMimeEq MimeJSON (Proxy :: Proxy MembersAvatar)
      propMimeEq MimeJSON (Proxy :: Proxy MembersAvatarSource)
      propMimeEq MimeJSON (Proxy :: Proxy MembersBio)
      propMimeEq MimeJSON (Proxy :: Proxy MembersBoardBackgrounds)
      propMimeEq MimeJSON (Proxy :: Proxy MembersBoardStars)
      propMimeEq MimeJSON (Proxy :: Proxy MembersBoardStarsIdBoard)
      propMimeEq MimeJSON (Proxy :: Proxy MembersBoardStarsPos)
      propMimeEq MimeJSON (Proxy :: Proxy MembersCustomBoardBackgrounds)
      propMimeEq MimeJSON (Proxy :: Proxy MembersCustomEmoji)
      propMimeEq MimeJSON (Proxy :: Proxy MembersCustomStickers)
      propMimeEq MimeJSON (Proxy :: Proxy MembersFullName)
      propMimeEq MimeJSON (Proxy :: Proxy MembersInitials)
      propMimeEq MimeJSON (Proxy :: Proxy MembersOneTimeMessagesDismissed)
      propMimeEq MimeJSON (Proxy :: Proxy MembersSavedSearches)
      propMimeEq MimeJSON (Proxy :: Proxy MembersSavedSearchesName)
      propMimeEq MimeJSON (Proxy :: Proxy MembersSavedSearchesPos)
      propMimeEq MimeJSON (Proxy :: Proxy MembersSavedSearchesQuery)
      propMimeEq MimeJSON (Proxy :: Proxy MembersUsername)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsEmailPosition)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsIdEmailList)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsShowListGuide)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsShowSidebar)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsShowSidebarActivity)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsShowSidebarBoardActions)
      propMimeEq MimeJSON (Proxy :: Proxy MyPrefsShowSidebarMembers)
      propMimeEq MimeJSON (Proxy :: Proxy Notifications)
      propMimeEq MimeJSON (Proxy :: Proxy NotificationsUnread)
      propMimeEq MimeJSON (Proxy :: Proxy Organizations)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsDesc)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsDisplayName)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsLogo)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsMembers)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsMembersDeactivated)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsMemberships)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsName)
      propMimeEq MimeJSON (Proxy :: Proxy OrganizationsWebsite)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsAssociatedDomain)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsBackground)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsBoardVisibilityRestrict)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsCalendarFeedEnabled)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsCardAging)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsCardCovers)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsColorBlind)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsComments)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsExternalMembersDisabled)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsGoogleAppsVersion)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsInvitations)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsLocale)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsMinutesBetweenSummaries)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsOrgInviteRestrict)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsPermissionLevel)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsSelfJoin)
      propMimeEq MimeJSON (Proxy :: Proxy PrefsVoting)
      propMimeEq MimeJSON (Proxy :: Proxy Sessions)
      propMimeEq MimeJSON (Proxy :: Proxy SessionsStatus)
      propMimeEq MimeJSON (Proxy :: Proxy TokensWebhooks)
      propMimeEq MimeJSON (Proxy :: Proxy Webhooks)
      propMimeEq MimeJSON (Proxy :: Proxy WebhooksActive)
      propMimeEq MimeJSON (Proxy :: Proxy WebhooksCallbackURL)
      propMimeEq MimeJSON (Proxy :: Proxy WebhooksDescription)
      propMimeEq MimeJSON (Proxy :: Proxy WebhooksIdModel)
      
